### PR TITLE
Update rides.csr

### PR DESCRIPTION
**Pull request by brenyodani**
I lost my certificates for the application during an update, could you  rewoke my certificate please? 

Thank you in advance!

### Checklist

- Please include a link to your app repository
https://github.com/nextcloud/app-certificate-requests/tree/master/rides

### CODE REVIEW

**Comment by bigcat88** [comment]
probably this issue(https://github.com/nextcloud/appstore/issues/1236) should be here?

**Comment by brenyodani** [comment]
Yeah I didn't know where I should ask you guys about rewoking the certificate, so I created both issues. How should I resolve it?

**Comment by mgallien** [comment]
@brenyodani the entry point is there
I am sorry for the late reply as I was busy
I will do it now

**Comment by mgallien** [comment]
@brenyodani You can find the new certificate here 6ad3b51098c99ed7d9d3eed15cc225dcf03ae2d4

**Comment by brenyodani** [comment]
@mgallien  @bigcat88  Thank you guys for the help!

**Pull request merged**
