### PR TITLE
Add certificate request for files_zip

### PR DESCRIPTION
**Pull request by juliushaertl**
Repo at https://github.com/nextcloud/files_zip

### CODE REVIEW

**Review by mgallien — APPROVED** [review]

**Comment by mgallien** [comment]
@juliushaertl do you expect more from me here ?

**Comment by juliushaertl** [comment]
@mgallien I'd need a certificate to be generated from the CSR in order to publish the app to the app store. I though maybe @blizzz has involved you there as part of the sysadmin process, but if not that can wait a bit :)

**Comment by mgallien** [comment]
> @mgallien I'd need a certificate to be generated from the CSR in order to publish the app to the app store. I though maybe @blizzz has involved you there as part of the sysadmin process, but if not that can wait a bit :)

will do it
@blizzz has given me the proper documentation

**Comment by mgallien** [comment]
[12bd554](https://github.com/nextcloud/app-certificate-requests/commit/12bd55459394181a187802ffcf1c33fd46dbaee6)

**Comment by juliushaertl** [comment]
Thank you :)

**Pull request merged**
