### PR TITLE
feat: add cidgravity_gateway.csr

### PR DESCRIPTION
**Pull request by FlorianRuen**
### Checklist

- The app repository is https://github.com/CIDgravity/nextcloud-cidgravity-gateway-app

### CODE REVIEW

**Comment by FlorianRuen** [comment]
Sorry, but can anyone look at this? Thanks

**Comment by FlorianRuen** [comment]
Hello there,

I wanted to kindly check if someone is available to review and merge the pull request.
I opened almost a month ago and this update is becoming critical for my work!

Thanks you! 🙏

**Comment by FlorianRuen** [comment]
@camilasan thank you, just fixed, you can re-check if it's enought for you!

**Comment by FlorianRuen** [comment]
@camilasan can you please review the changes ? thanks a lot

**Comment by GretaD** [comment]
done, cert can be found here 5682e1c89b6528a82e79b2b472fe02ec8d93710d

**Pull request merged**
