### PR TITLE
App Signing Certificate

### PR DESCRIPTION
**Pull request by ayselafsar**
@MorrisJobke
Could you please send me the certificate to sign my application?

### CODE REVIEW

**Comment by MorrisJobke** [comment]
8d3051e

**Comment by MorrisJobke** [comment]
@ayselafsar BTW: Do you already have a source code repo somewhere?

**Comment by ayselafsar** [comment]
@MorrisJobke Thanks for the certificate! You can find the source code here: https://github.com/ayselafsar/dicomviewer

**Comment by MorrisJobke** [comment]
@ayselafsar Nice - even with screenshots 👍 

@karlitschek Something for your story telling 😉 https://en.wikipedia.org/wiki/DICOM

**Comment by MorrisJobke** [comment]
Maybe @rullzer can give you some hints how to integrate it into our preview system so that the files have proper thumbnails once your app is installed 😉

**Comment by rullzer** [comment]
Well not if it is JS only the viewer. But @ayselafsar please join #nextcloud-dev on freenode so we can discuss it :)

**Pull request merged**
