### PR TITLE
Create data.csr

### PR DESCRIPTION
**Pull request by Rello**
@MorrisJobke

Data Analytics for Nextcloud
From datasouce to reporting. Data Analytics provides modular datasources, a realtime or storage backend and flexibile visualization.
https://github.com/rello/data

### CODE REVIEW

**Comment by nickvergessen** [comment]
Not sure if `data` is a good app id. Maybe `data_visualization` is a better one?

**Comment by Rello** [comment]
Hello
Thank you for your reply
Visualization is just one small part. You can check the architecture picture in the repo. 

Its about data collecting, transforming, reporting, sharing...

Also technically quite a challenge to refactor the whole app now. 

Where do you see issues with the naming?

**Comment by blizzz** [comment]
Then data-analytics perhaps? I agree, data itself is quite short and meaningless.

**Comment by Rello** [comment]
I am planning to come to the NC office on thursday. Lets discuss in person

**Comment by Rello** [comment]
What about just „analytics“?

**Comment by blizzz** [comment]
fine with me

**Comment by Rello** [comment]
as discussed at the hackweek
=>
https://github.com/nextcloud/app-certificate-requests/pull/275

**Pull request closed without merging**
