### PR TITLE
Create secrets.csr

### PR DESCRIPTION
**Pull request by theCalcaholic**
### Repository

The source for the Secrets app is located here: https://github.com/theCalcaholic/nextcloud-secrets

### Description

This app adds E2E encrypted secret sharing functionality to nextcloud (similar to Firefox Send, but with text fields instead of files (so far)).

image

Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>

### CODE REVIEW

**Review by vitormattos — APPROVED** [review]
Excellent app!

**Comment by vitormattos** [comment]
Put the screenshot in your readme and in your info.xml

**Comment by theCalcaholic** [comment]
@vitormattos Good point, will do :)

**Comment by vitormattos** [comment]
Your crt file: c7f3c0dd3557a5bed59751da6b3fbd5c9e549191

**Comment by vitormattos** [comment]
Maybe, could be my first contribution to your app :-)

**Pull request merged**
