### PR TITLE
Create editwithoffice.csr

### PR DESCRIPTION
**Pull request by burningscript**

### CODE REVIEW

**Comment by mgallien** [comment]
@burningscript can you provide a link to your application source repository ?

**Comment by burningscript** [comment]
> @burningscript can you provide a link to your application source repository ?

Sure:
https://github.com/burningscript/editfileswithoffice

**Comment by blizzz** [comment]
@burningscript the certificate request file name must mach with your app id.

**Comment by mgallien** [comment]
@burningscript gentle ping

**Comment by vitormattos** [comment]
ping @burningscript

**Comment by burningscript** [comment]
sorry lost my github client on desktop, I dont know how to change it and recreate the key

**Comment by vitormattos** [comment]
https://nextcloudappstore.readthedocs.io/en/latest/developer.html#publishing-apps-on-the-app-store
https://github.com/nextcloud/app-certificate-requests#readme

**Comment by vitormattos** [comment]
Hi @burningscript,
Do you have news?
Do you already generated the cert with the right name?

**Comment by vitormattos** [comment]
ping @burningscript

**Pull request closed without merging**
