### PR TITLE
Create blockscores.csr

### PR DESCRIPTION
**Pull request by Rello**
@MorrisJobke

https://github.com/Rello/blockscores-app
thanks

### CODE REVIEW

**Comment by MorrisJobke** [comment]
2bd0779

**Comment by Rello** [comment]
@MorrisJobke do you have known issues with the appstore?
I cant register a new app. getting timeouts on 
https://apps.nextcloud.com/api/v1/apps/releases

**Comment by MorrisJobke** [comment]
> @MorrisJobke do you have known issues with the appstore?
> I cant register a new app. getting timeouts on

Could you try again?

**Comment by Rello** [comment]
now it worked.
thank you!

**Pull request merged**
