### PR TITLE
Fbsync

### PR DESCRIPTION
**Pull request by skjnldsv**
@LukasReschke 
Thanks :)

### CODE REVIEW

**Comment by LukasReschke** [comment]
Can you move that to the subfolder fbsync? Thank you! :)

**Comment by nickvergessen** [comment]
Moved it

**Comment by LukasReschke** [comment]
Thanks. The certificate can be found at https://github.com/nextcloud/app-certificate-requests/blob/master/fbsync/fbsync.crt

**Comment by skjnldsv** [comment]
👍

**Pull request merged**
