### PR TITLE
Create activitylog.csr

### PR DESCRIPTION
**Pull request by hellix08**
@LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Do you have a link to that app somewhere?

**Comment by hellix08** [comment]
Yes, here's a tar.gz of the app folder:
https://drive.google.com/open?id=0B1aDM-Dj36QyWFVBc2dzdzhHQTg

**Comment by hellix08** [comment]
The app is now available on ownCloud:
https://apps.owncloud.com/content/show.php?content=174809

@LukasReschke

**Comment by LukasReschke** [comment]
https://github.com/nextcloud/app-certificate-requests/blob/7aa5ea7c79056e6ac8953184917ff73ba749174c/activitylog/activitylog.crt

**Comment by hellix08** [comment]
Thanks 😃

**Pull request merged**
