### PR TITLE
Pax Fax certificate signing request

### PR DESCRIPTION
**Pull request by DoubleBastionAdmin**
Pax Fax is a Nextcloud application that allows sending and receiving faxes in Nextcloud.
It connects to a phaxio.com account and needs a phone number from Phaxio.
The git repository where the app is developed is [on our server](https://git.doublebastion.com/pax-fax/).

We have no affiliation with Phaxio.

Our [contact page](https://www.doublebastion.com/contact/).

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @DoubleBastionAdmin 
Can you split in separated PR to make the PR more specific?

**Comment by DoubleBastionAdmin** [comment]
@vitormattos  thank you for your reply. I split the single pull request into 3 separate pull requests.

**Comment by vitormattos** [comment]
Your branch come with old commits as new commits.
Try to run git rebase or, maybe, recreate your branch. Will be very easy work to delete locally the branch, create, do a new commit and do a force push.

**Comment by DoubleBastionAdmin** [comment]
OK. Just a sec.

**Comment by vitormattos** [comment]
Here: https://github.com/nextcloud/app-certificate-requests/commit/126fba16c9a007950da6a78241019602d48a0518

**Pull request merged**
