### PR TITLE
Add mailnotifier

### PR DESCRIPTION
**Pull request by vevedh**
### Checklist

- App url : https://github.com/vevedh/mailnotifier.git
https://github.com/vevedh/mailnotifier.git

### CODE REVIEW

**Comment by vitormattos** [comment]
What PR I need to consider?
Is this duplicated of https://github.com/nextcloud/app-certificate-requests/pull/600 ?

**Comment by vevedh** [comment]
> Quel PR dois-je considérer? Est-ce un doublon de #600 ?

Yes sorry , can you give me a publique key please. I'm french not speak english very well

**Review by vitormattos — APPROVED** [review]

**Comment by vitormattos** [comment]
Don't worry about English, I'm not native English speaker too.

**Comment by vitormattos** [comment]
Your crt file: 6abad1d82c5f5a6a6326c091a9c3817ef0f01558

**Pull request merged**
