### PR TITLE
New owner for the bbb application

### PR DESCRIPTION
**Pull request by zak39**
Hi everyone,

We want to change the owner of the bbb app and @sualko agrees.

The repository link : https://github.com/littleredbutton/cloud_bbb

The issue to inform the change owner : https://github.com/littleredbutton/cloud_bbb/issues/269

Please, possible to resolve this PR quickly.

### CODE REVIEW

**Comment by sualko** [comment]
Since I have no time to maintain the app anymore, it would be great if the folks from Arawa could take over :+1:

**Comment by pielonet** [comment]
Please consider merging this pull request which was validated by the former app maintainer.

**Comment by GretaD** [comment]
we are trying, but there was an issue, sorry its taking forever, but i will try to finish this one today.

**Comment by GretaD** [comment]
here its the certificate 8e33bde489e25a3870b59b875f3217b9b7561582

**Comment by zak39** [comment]
> here its the certificate [8e33bde](https://github.com/nextcloud/app-certificate-requests/commit/8e33bde489e25a3870b59b875f3217b9b7561582)

Thanks @GretaD for your help :slightly_smiling_face:

**Pull request merged**
