### PR TITLE
Add emlviewer.csr

### PR DESCRIPTION
**Pull request by GabrielDornianu**
@MorrisJobke

### CODE REVIEW

**Comment by nickvergessen** [comment]
Do you have a link to the repository?

**Comment by GabrielDornianu** [comment]
Yes, of course,  I added you as a contributor.
Please check out the following url:
https://github.com/GabrielDornianu/emlviewer

**Comment by GabrielDornianu** [comment]
Is it okay ? Do i need to add something or remove something ?

**Comment by blizzz** [comment]
@GabrielDornianu  Is there a reason the repo is not generally open?

**Comment by MorrisJobke** [comment]
Exists nowadays already: #280

**Pull request closed without merging**
