### PR TITLE
add files_ebookreader csr

### PR DESCRIPTION
**Pull request by onny**

### CODE REVIEW

**Comment by onny** [comment]
I created an ebook reader app, source is here https://git.project-insanity.org/onny/web-nextcloud-app-files_ebookreader
Would be really cool if you signe this :)

**Comment by onny** [comment]
@MorrisJobke

**Comment by blizzz** [comment]
Hi @onny, the repo requires an account. Is your app somehow related to https://apps.nextcloud.com/apps/files_reader ? The app IDs are somewhat similar.

**Comment by onny** [comment]
@blizzz oh sorry, I fixed it, the repo is now accessable. I forked the pdfviewer app for this one but don't know where to set the appid.

**Comment by blizzz** [comment]
> @blizzz oh sorry, I fixed it, the repo is now accessable. 

Thanks!

> I forked the pdfviewer app for this one but don't know where to set the appid.

Why, you did :) https://git.project-insanity.org/onny/web-nextcloud-app-files_ebookreader/blob/master/appinfo/info.xml#L3

It's fine, you can leave it like that. I just wondered whether there was any relation.

i'll generate the certificate for you.

**Comment by blizzz** [comment]
@onny here you go: https://github.com/nextcloud/app-certificate-requests/commit/17019da621141554489848d1609c323b595c002d

**Pull request merged**
