### PR TITLE
Create pride.csr

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Comment by rullzer** [comment]
Nice app.
You should be proud

**Comment by blizzz** [comment]
repo url?

**Comment by nickvergessen** [comment]
https://github.com/skjnldsv/pride

**Comment by MorrisJobke** [comment]
@skjnldsv There was a problem on our side when the certificates were generated. There are a few certificates that have the same serial number. For now this is nothing to worry about right now, but once one certificate gets revoked all certificates with the same serial number won't work anymore. Thus I would ask you to take this new certificate for your app: cc5fc6c. You key is still the same and the old certificate still works, but it might be that due to a revocation in the future the current one might be revoked as well. So please use the new one. Sorry for the inconvenience.

**Pull request merged**
