### PR TITLE
Add diary.csr

### PR DESCRIPTION
**Pull request by danielroehrig**
Hi there,
I built a basic diary for nextcloud that I would like to share.
Cheers
Daniel

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @danielroehrig ! Excellent! Congratulations for your app.

Can you share here the link of repository?

You need fix the DCO:
https://github.com/nextcloud/app-certificate-requests/pull/505/checks?check_run_id=5413432100

**Comment by danielroehrig** [comment]
Hi @vitormattos 
I rebased - and hopefully signed - the commit. The repository can be found here: https://github.com/danielroehrig/nextcloud-diary

**Comment by vitormattos** [comment]
Good! All tests is ok now.

I received not found when trying to access the repository.

**Comment by danielroehrig** [comment]
That's because sometimes I do dumb stuff like setting my repository to private. Sorry. Please tell me it's visible now.

**Comment by vitormattos** [comment]
Hi @danielroehrig 

Will be good if the repository name follow the same name of app_id.

Motivation:
When a new developer clone your repository to start work, if the repository have a different name of app_id, the new developer will need rename the folder or clone into a folder with the same name of app_id to work.

I will wait your opinion about the suggestion because if you accept, you will need generate a new certificate and change this PR.

**Comment by danielroehrig** [comment]
So, I should change the name of the repository to "danielroehrig/diary" then? That's no problem. Done: https://github.com/danielroehrig/diary
But since the name of the certificate is already "diary.csr", I don't need to change the PR, right?

**Comment by vitormattos** [comment]
> But since the name of the certificate is already "diary.csr", I don't need to change the PR, right?
Right.

Now you can start to work only doing a clone of your repository inside app folder. Will be more easy.

**Comment by danielroehrig** [comment]
I have a working setup already where I have my repository cloned inside the custom_apps folder and then created a docker setup so that development is pretty easy right now. Do I need to change anything then?

My main goal is to get this very first version into the app store as soon as possible, so that I and other can use it. Should I just wait for the merge to complete and then upload the tar.gz to the store? How can I test, if the creation of the tar.gz was succesful locally?

**Comment by vitormattos** [comment]
> Should I just wait for the merge to complete and then upload the tar.gz to the store?

Yes and not. I'm creating your crt file. You will need configure your crt on appstore API.

> How can I test, if the creation of the tar.gz was succesful locally?

You will need sign your app:
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/code_signing.html
If you want implement automation to make this more easy:
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/release_automation.html

**Comment by vitormattos** [comment]
crt here: https://github.com/nextcloud/app-certificate-requests/commit/04b53d5723b6355bc107b309188ea85942bcbe34

**Pull request merged**
