### PR TITLE
Create nextbackup.csr

### PR DESCRIPTION
**Pull request by pbek**
repo: https://github.com/pbek/nextbackup

I have to rename ownbackup to nextbackup.
I got a letter from https://www.ownbackup.com/. :grimacing:

### CODE REVIEW

**Comment by pbek** [comment]
@MorrisJobke, thank you

**Comment by blizzz** [comment]
@pbek here you go d24d0bb64697afd1ca431698db64af54da008840

**Comment by blizzz** [comment]
@rullzer i think you can do the revoke dance around the old ownbackup cert then

**Comment by pbek** [comment]
@blizzz thank you very much!

**Comment by pbek** [comment]
Is there a way I can "unpublish", disable or archive the ownBackup store page?

**Comment by blizzz** [comment]
@pbek looks like i can only totally delete it…

**Comment by blizzz** [comment]
or i could possibly rename it, however you got already the new one up.

**Comment by pbek** [comment]
@blizzz, renaming sounds great too, in that case you will delete NextBackup, rename OwnBackup to NextBackup and I will simply publish the latest release again, right? If yes, please go for it.

**Comment by blizzz** [comment]
@pbek I did the changes. Alas, the admin panel behaves strange, it  appears both app ids are present now :-/ The search shows ownbackup only. Please try to publish the release… if this fails, it indeed has to be the new entry I am afraid.

I am off the next days, in doubt ping @rullzer for so long.

**Comment by pbek** [comment]
@blizzz thank you very much, I'll try on Saturday!

**Comment by pbek** [comment]
@blizzz, @rullzer Seems like I can't push a new release now.

When using the ownbackup cert I get a `App id nextbackup does not match cert CN ownbackup`
When using the nextbackup cert I get a `Signature is invalid: [('rsa routines', 'RSA_padding_check_PKCS1_type_1', 'invalid padding'), ('rsa routines', 'rsa_ossl_public_decrypt', 'padding check failed')]`.

I also tried re-packaging, uploading and signing again. Same result.
So I guess you will have to remove the current NextBackup app again so I can push a fresh one.

**Comment by pbek** [comment]
@blizzz, @rullzer any news? 😬

**Comment by rullzer** [comment]
It seems the certificate doesn't match let me have a look

**Comment by rullzer** [comment]
Yes. Please try again. If it still fails I will just ermove ownBackup

**Comment by pbek** [comment]
@rullzer, the upload worked and https://apps.nextcloud.com/apps/nextbackup has the current release, but it seems to be a fresh application, no comments of ownbackup are present.

https://apps.nextcloud.com/apps/ownbackup still exists with comments and so on.

**Comment by pbek** [comment]
Any news on the removal? :grin:

**Comment by MorrisJobke** [comment]
@pbek There was a problem on our side when the certificates were generated. There are a few certificates that have the same serial number. For now this is nothing to worry about, but once one certificate gets revoked all certificates with the same serial number won't work anymore. Thus I would ask you to take this new certificate for your app: 8e060f7. You key is still the same and the old certificate still works, but it might be that due to a revocation in the future the current one might be revoked as well. So please use the new one. Sorry for the inconvenience.

**Comment by pbek** [comment]
Thank you @MorrisJobke, I will then from now on (next release of NextBackup) use the new `nextbackup.crt`.

**Comment by MorrisJobke** [comment]
> Thank you @MorrisJobke, I will then from now on (next release of NextBackup) use the new `nextbackup.crt`.

@pbek Perfect :)

**Pull request merged**
