### PR TITLE
new signlive.csr

### PR DESCRIPTION
**Pull request by intarsys-nc**
please add our signlive.csr

### CODE REVIEW

**Comment by intarsys-nc** [comment]
Hi,

we plan to administrate the code for the app in gitlab.
So all links in the application.info will lead to gitlab.
Is this a problem? Do we have to consider some special requirements then?

How can we control the moment of publishing?
As I understood I upload a signed app.tar and - at some magic moment ;-) -  the app appears in the app store?

If you need more information about the app, please contact me.

Thanks, Jörg Steinbach.
intarsys GmbH
jsteinbach@intarsys.de
+49 173 3218 444

**Comment by mgallien** [comment]
Hello,

sorry for the delay
> Hi,
> 
> we plan to administrate the code for the app in gitlab. So all links in the application.info will lead to gitlab. Is this a problem? Do we have to consider some special requirements then?

we just need to have a link here to your application source repository before creating the certificate.
it can be hosted on gitlab without any problems

> How can we control the moment of publishing? As I understood I upload a signed app.tar and - at some magic moment ;-) - the app appears in the app store?

I cannot reply as I am not familiar enough with the app publishing workflow. sorry

> If you need more information about the app, please contact me.
> 
> Thanks, Jörg Steinbach. intarsys GmbH [jsteinbach@intarsys.de](mailto:jsteinbach@intarsys.de) +49 173 3218 444

**Comment by marcelklehr** [comment]
> How can we control the moment of publishing? As I understood I upload a signed app.tar and - at some magic moment ;-) - the app appears in the app store?

As soon as you upload the app bundle it will be available on the store.

**Comment by intarsys-nc** [comment]
Hi Matthieu,
the repository link is https://gitlab.com/intarsys/signlive.
I just invited you for the repository.
For the moment we are testing and offering the app only to "curious" customers.
I think we open it for the public in April.

**Comment by mgallien** [comment]
> Hi Matthieu, the repository link is https://gitlab.com/intarsys/signlive. I just invited you for the repository. For the moment we are testing and offering the app only to "curious" customers. I think we open it for the public in April.

Hello, @intarsys-nc 
sorry forgot to reply.

I am not seeing your code and wanted to make sure the certificate id and the app id are the same.
Can you check yourself ?
If they match I can then issue the certificate quickly.

Sorry for the delay

**Comment by intarsys-nc** [comment]
Hi Matthieu,

my fault. I changed your gitlab role to reporter. Now you should have access to the repository https://gitlab.com/intarsys/signlive .

If it still doesn't work, I attached our app's info.xml as info.txt

[info.txt](https://github.com/nextcloud/app-certificate-requests/files/7933414/info.txt)

**Comment by mgallien** [comment]
> Hi Matthieu,
> 
> my fault. I changed your gitlab role to reporter. Now you should have access to the repository https://gitlab.com/intarsys/signlive .
> 
> If it still doesn't work, I attached our app's info.xml as info.txt
> 
> [info.txt](https://github.com/nextcloud/app-certificate-requests/files/7933414/info.txt)

you can find the certificate here 5f50e912b1cdc7ceae3220b255f2c7a5ca59e773

**Pull request merged**
