### PR TITLE
Create scanner2.csr

### PR DESCRIPTION
**Pull request by TSmith00077**

### CODE REVIEW

**Comment by blizzz** [comment]
Is it related to scanner? Do you have a public repo?

**Comment by TSmith00077** [comment]
I have modified the programs on scanner, but there are is certificate error without signature by system.
What can I do?

**Comment by blizzz** [comment]
So are your changes based on https://github.com/e-alfred/nextcloud-scanner? Did you try to get them into that project?

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket.

**Pull request closed without merging**
