### PR TITLE
New owner for files_bpm

### PR DESCRIPTION
**Pull request by kirstenhh**
I am taking over for Harald Loydl (contact at harald.loydl@loydl.ch) on the BPM Files app. As such, I'm submitting a new certificate. 
App repository:  https://github.com/kirstenhh/nc-bpm-app

Signed-off-by: Kirsten <kirstenheidihauck@gmail.com>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Looking at https://github.com/Loydl/nc-bpm-app/issues it sounds like a good idea.

**Comment by vitormattos** [comment]
@kirstenhh could you open first an issue here: https://github.com/Loydl/nc-bpm-app/issues, and interact with Harald Loydl to get the approve of him?
Don't worry, this is only a security check in cases similar of this to prevent problems.

**Comment by kirstenhh** [comment]
@vitormattos So you guys can see it? Sure, I'll ask him to respond on the issue itself

**Comment by nickvergessen** [comment]
From my POV it's not necessary to get confirmation. Last release was in April 2021 and all questions for new versions were unanswered.

**Comment by vitormattos** [comment]
Hi @kirstenhh, the maintainer approved!

https://github.com/Loydl/nc-bpm-app/issues/13

Good!

Only doing suggestion, I think that now you have two ways to go:
1. request a [transfer ownership of repository ](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) to maintainer.
2. create a fork of repository and post on all issues that now have a new repository with the code of this app. And I think that also will be good to put on README or in other place, thanks to first maintainer.

I will start now the flow here to generate the new certificate to this app.

**Comment by kirstenhh** [comment]
Thank you! I have a fork already set up, but I'll post on the issues as well.

**Review by vitormattos — APPROVED** [review]

**Comment by vitormattos** [comment]
Your crt file: b0744305a2a1f2557b4b89eca6020a09b553d40c

**Pull request merged**
