### PR TITLE
hancomoffice new csr file

### PR DESCRIPTION
**Pull request by TYRakeshN**
Signed-off-by: RakeshN <rakeshgowda3101@gmail.com>

@MorrisJobke  new csr file

### CODE REVIEW

**Comment by TYRakeshN** [comment]
source code link https://github.com/hancom-git/hancom-nextcloud

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
5623984

**Comment by TYRakeshN** [comment]
Hi @MorrisJobke , what is the folder structure to be followed when uploading the app to nextcloud app store? currently i have been following  "projectName\home\appinfo\info.xml". But when uploading it i am getting error stating unable to get path "\home\appinfo\info.xml". could you pls guide ?

**Comment by MorrisJobke** [comment]
> Hi @MorrisJobke , what is the folder structure to be followed when uploading the app to nextcloud app store? currently i have been following "projectName\home\appinfo\info.xml". But when uploading it i am getting error stating unable to get path "\home\appinfo\info.xml". could you pls guide ?

it should be the plain app directory. Like you can see for example in here: https://github.com/nextcloud/serverinfo

So there needs to be an appinfo/ folder in the root.

**Comment by TYRakeshN** [comment]
even after having same structure i am facing above error . does the app name having "-" affect the uplaod?

**Comment by TYRakeshN** [comment]
yes app name is "hancomoffice".  repository name has "-" in it as "hancom-nextcloud".  In the web interface i was able to register the app successfully but during uploading of the app i am facing the error **"No possible app folder found. App folder must contain only lowercase ASCII characters or underscores"**  .  the app structure follows all guide lines & its in same structure as you gave a example of "nextcloud/serverinfo".  even after multiple trials & re-edits, corrections facing same issue.

**Comment by MorrisJobke** [comment]
Could you provide the archive?

**Comment by TYRakeshN** [comment]
https://hancom-nextcloud-appstore.s3.ap-northeast-2.amazonaws.com/hancomnextcloud.tar.gz

**Comment by MorrisJobke** [comment]
Okay - this looks just fine. Also I could not spot any obvious issues. I assume you just paste this link in there, then the signature and press the button, right?

Bildschirmfoto 2021-05-27 um 16 52 17

**Comment by TYRakeshN** [comment]
yes correct.

**Comment by marcelklehr** [comment]
> hancom-nextcloud-appstore.s3.ap-northeast-2.amazonaws.com/hancomnextcloud.tar.gz

Top-level folder is `.`

**Comment by TYRakeshN** [comment]
" ./application  "    as a part of my earlier request i had issue with submission then support team suggested me to use relative path rather than absolute path while doing tarball so i took the relative path " ./hancomnextcloud "

**Comment by blizzz** [comment]
the top folder name has to match the appid iirc.

**Comment by TYRakeshN** [comment]
https://hancom-nextcloud-appstore.s3.ap-northeast-2.amazonaws.com/hancomoffice.tar.gz   changed archive as per the appid name & registration was success but upload showing same error  **No possible app folder found. App folder must contain only lowercase ASCII characters or underscores**    
image

**Comment by MorrisJobke** [comment]
I just checked the file of the news app and it is exactly the same. https://apps.nextcloud.com/apps/news

It is also an tar.gz with the same structure. Is there maybe some invisible character in there? After extraction it also matches the regular expression `^[a-z]+$` :/ 


The message is raised in here:

https://github.com/nextcloud/appstore/blob/77e2d33f2318c493b6c38a10d1f81dfca8556339/nextcloudappstore/api/v1/release/parser.py#L143-L149

That means that no folder is found by `find_app_folders`:

https://github.com/nextcloud/appstore/blob/77e2d33f2318c493b6c38a10d1f81dfca8556339/nextcloudappstore/api/v1/release/parser.py#L155-L159

This basically returns the foldername if it matches the regex.

The regex is defined in https://github.com/nextcloud/appstore/blob/77e2d33f2318c493b6c38a10d1f81dfca8556339/nextcloudappstore/api/v1/release/parser.py#L59

And it is `^[a-z]+[a-z0-9_]*(?:/.*)*$` ... so it should match :/

**Comment by TYRakeshN** [comment]
There are no extra spaces/open characters blocking. verified it

**Comment by MorrisJobke** [comment]
@blizzz Do you see anything wrong in the archive?

**Comment by TYRakeshN** [comment]
updated archive link https://hancom-nextcloud-appstore.s3.ap-northeast-2.amazonaws.com/hancomoffice.tar.gz

**Comment by blizzz** [comment]
> @blizzz Do you see anything wrong in the archive?

IIRC earlier the folder name was wrong, but in the latest this seems to be OK.

@TYRakeshN please exclude the .git folder from the tarball, and also the tarball within the tarball :)

**Comment by TYRakeshN** [comment]
removed the .git & tarball and tried to upload still same issue.   
image     https://hancom-nextcloud-appstore.s3.ap-northeast-2.amazonaws.com/hancomoffice.tar.gz

**Comment by marcelklehr** [comment]
@TYRakeshN I think it would be beneficial if you looked at the output with an archive viewer.

**Comment by blizzz** [comment]
@TYRakeshN how did you create the tarballs?

I compared with the latest upload on the app store (user_backend_sql_raw) and ran the code in a python shell. In user_backend_sql_raw the folder on the top level is simply:

```
user_backend_sql_raw
user_backend_sql_raw/LICENSE
user_backend_sql_raw/README.md
...
```

In your case however it is:

```
./hancomoffice
./hancomoffice/AUTHORS.md
./hancomoffice/CHANGELOG.md
```

See the leading `./`.

In Ark it looks completely the same, but it looks internally the  names/pathes are stored differently.

**Comment by MorrisJobke** [comment]
The news app for example does it like this:

```
tar -czf $(appstore_package_name).tar.gz -C $(appstore_sign_dir) $(app_name)
```
https://github.com/nextcloud/news/blob/master/Makefile#L188

**Comment by TYRakeshN** [comment]
i used **tar -czf hancomoffice.tar.gz -C hancomoffice hancomoffice**

**Comment by TYRakeshN** [comment]
I used **tar cvfz hancomoffice.tar.gz ./hancomoffice/**

**Comment by blizzz** [comment]
Use `tar --list -zf hancomoffice.tar.gz` to check your contents. 

`tar -cvzf hancomoffice.tar.gz hancomoffice/` should give you the desired result.

**Comment by TYRakeshN** [comment]
Thanks @blizzz @MorrisJobke . it worked **tar -cvzf hancomoffice.tar.gz hancomoffice/** with this.

**Pull request merged**
