### PR TITLE
Create berichtsheft.csr

### PR DESCRIPTION
**Pull request by jonasfrick**
Signed-off-by: Jonas Frick <66498092+jonasfrick@users.noreply.github.com>

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @jonasfrick could you share here the URL to the repository of your new app?

**Comment by jonasfrick** [comment]
Of course.

https://github.com/jonasfrick/NextCloud-Berichtsheft-App

**Comment by vitormattos** [comment]
@jonasfrick is this a private repository? Could you use an open source license and make the repository public?
For example: https://www.gnu.org/licenses/agpl-3.0.txt and putting in a file called LICENSE in root folder of your app

**Comment by jonasfrick** [comment]
I added the LICENSE and published the repo

**Comment by vitormattos** [comment]
Yuhuuuuu! Excelent!

**Comment by vitormattos** [comment]
Your crt here: aa3fb359ace0e026fe808f97475e98af32ef6129
Welcome as a Nextcloud app developer!

**Pull request merged**
