### PR TITLE
Create google_synchronization.csr

### PR DESCRIPTION
**Pull request by MarcelRobitaille**
Signed-off-by: Marcel Robitaille <marcelrobitaille11@gmail.com>

### Checklist

- Please include a link to your app repository: https://github.com/MarcelRobitaille/nextcloud_google_synchronization

### CODE REVIEW

**Comment by MarcelRobitaille** [comment]
This is a fork of https://github.com/nextcloud/integration_google

A member of that app recommended that I publish this fork: https://github.com/nextcloud/integration_google/pull/93

**Comment by vitormattos** [comment]
Hi @MarcelRobitaille
The folder/file.crt need to have the same name as your `APP_ID`

Looking into your [info.xml](https://github.com/MarcelRobitaille/nextcloud_google_synchronization/blob/master/appinfo/info.xml#L3) file I identified other `APP_ID`

Identify what will be your APP_ID and do the necessary changes. Or rename the folder/file to `google_synchronization` on this PR or replace your APP_ID by `synchronization_google`).

**Comment by MarcelRobitaille** [comment]
Sorry about that @vitormattos. Should be good now

**Review by vitormattos — APPROVED** [review]

**Comment by vitormattos** [comment]
CRT commit: 8e8a8cc81957ea6019835ec3b1c5e5d034b5dcb9

**Pull request merged**
