### PR TITLE
Create metadatarepo

### PR DESCRIPTION
**Pull request by holzheu**
CSR for metadatarepo. 

https://github.com/BayCEER/metadatarepository

### CODE REVIEW

**Comment by holzheu** [comment]
@MorrisJobke 
App is currently signed with a owncloud certificate. We would like to try nextcloud.

**Comment by blizzz** [comment]
@holzheu please create the csr file as metadatarepository/metadatarepository.csr (the cert will be placed into that folder later)

**Comment by blizzz** [comment]
@holzheu we're getting closer :) we need the csr, the certificate request file. You'll get the crt from us.

**Comment by holzheu** [comment]
@blizzz Renamed the file. Sorry for picking the wrong name.

**Comment by blizzz** [comment]
here you go: 501b7501474efacaed7038e7999fb3cfa2112f11

**Pull request merged**
