### PR TITLE
Create testappstore.csr

### PR DESCRIPTION
**Pull request by XiaodiJiang**

### CODE REVIEW

**Comment by XiaodiJiang** [comment]
@LukasReschke Hi,Could you help to generate the crt? Thank you!

**Comment by BernhardPosselt** [comment]
Seems to be a test app correctly? What are you trying to achieve :)

**Comment by XiaodiJiang** [comment]
I followed the App Developer Guide to learn how to register an app,but it seems I've done something wrong.Sorry !

**Comment by BernhardPosselt** [comment]
Check https://nextcloudappstore.readthedocs.io/en/latest/developer.html#obtaining-a-certificate

You need to replace the APP_ID in the commands with your app's id (which in your case is testappstore right now but I doubt that this is your app id??)

**Comment by XiaodiJiang** [comment]
I have checked the link ,but I just want to upload apps to my own nextcloudappstore.
What should I do ? Should I follow the steps to generate a csr or somthing,and then commite it to this repository?
Thanks!

**Comment by BernhardPosselt** [comment]
> Should I follow the steps to generate a csr or somthing,and then commit it to this repository?

Exactly. That's also what you did but it seems that you've got your app id wrong.

**Comment by BernhardPosselt** [comment]
Maybe post us a link to your git repo then we can help you

**Pull request closed without merging**
