### PR TITLE
Replaces existing certificate (request)

### PR DESCRIPTION
**Pull request by RobertSecSign**
Hi @MorrisJobke,

I'm the new maintainer of our SecSign ID app and need to replace the cert to sign a new version.
Source code of the upcoming new version 0.3.2 can be found at the existing github repo: [SecSign/SecSign-ID-Nextcloud-Plugin](https://github.com/SecSign/SecSign-ID-Nextcloud-Plugin)

Let me know if I can provide more info regarding this replacement.

Kind regards,
Robert

### CODE REVIEW

**Comment by MorrisJobke** [comment]
From #225

**Comment by MorrisJobke** [comment]
@BjoernSecSign Mind to approve this?

**Comment by RobertSecSign** [comment]
Hi Morris,

thanks you so much for getting back to us about the request so quickly. And also thanks for not simply rubber-stamping this change.
Unfortunately we cannot get in contact with Björn until the end of the year as he is currently not working for us and he is completely off grid, otherwise we'd continue using the existing private cert.
In the meantime I'm the new maintainer of the app.

If you need further information please don't hesitate to ask.

Kind regards
Robert

**Comment by MorrisJobke** [comment]
> thanks you so much for getting back to us about the request so quickly. And also thanks for not simply rubber-stamping this change. Unfortunately we cannot get in contact with Björn until the end of the year as he is currently not working for us and he is completely off grid, otherwise we'd continue using the existing private cert. In the meantime I'm the new maintainer of the app.

That's fine. I would see the commit to the base repo as a valid proof for this request. https://github.com/SecSign/SecSign-ID-Nextcloud-Plugin/commit/2892fa170c26fe59262531cedcc9fffcf3efe3cf

In the worst case we will revoke it again if @BjoernSecSign sends a veto in here.

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
0c0dce3

**Pull request merged**
