### PR TITLE
CSR for app https://github.com/mlojewski-me/user_sql

### PR DESCRIPTION
**Pull request by mlojewski-me**
CSR for app [user_sql_2](https://github.com/mlojewski-me/user_sql)

I made a new version because the [old one](https://www.aboehler.at/hg/user_sql/) has not been updated for quite a while, and it is not available in any public repository where I can send my commits.

@MorrisJobke

### CODE REVIEW

**Comment by MariusBluem** [comment]
Can we maybe find a way, that @mlojewski-me is continuing `user_sql` instead of publishing a `_2`-app? @MorrisJobke 

cc @andyboeh for the initial app...

**Comment by andyboeh** [comment]
In the past, @Bubu already wanted to continue the development of the app. I even contacted the NextCloud team regarding the transfer of ownership, but we did never complete the transfer. I do not know what @Bubu is currently planning or whether he is still involved with user_sql. I'd be happy if someone continued the development of user_sql and released an official version.

**Comment by MariusBluem** [comment]
It seems like there are mutliple people interested in the development of this app. For now, we are talking about @Bubu and @mlojewski-me ... what do you think about creating a more-or-less official nextcloud/user_sql-repository over here, where everybody who wants to - can contribute?

This would make changing maintainers etc. in the future much more easy and would help keeping this app up-to-date.

**Comment by MariusBluem** [comment]
@mlojewski-me your info.xml is containing version number 1.0.0 ... there was a higher version in the past (2.x.x) ... if we make it happen to use `user_sql` as appid, we should consider releasing this with an higher version number, so that migration is possible.

**Comment by mlojewski-me** [comment]
I know, I will change it if we stick with the old appid.

**Comment by MariusBluem** [comment]
@mlojewski-me would you be ok with moving your repo to this GitHub-organization?

**Comment by mlojewski-me** [comment]
Yes it's fine for me. I think it's better to maintain this app in the official Nextcloud repository.

**Comment by mlojewski-me** [comment]
@MariusBluem I pushed a commit. I adopted application to the old appid. Now do you want me to transfer ownership of my repo to nextcloud organization?

**Comment by MariusBluem** [comment]
I will contact you via email.

**Comment by MariusBluem** [comment]
Moved, and can be now found over here: https://github.com/nextcloud/user_sql/ 😉 
@mlojewski-me 2nd task is to talk to @andyboeh to claim the certificate to publish the user_sql app in the future ... otherwise we would need to revoke - and re-generate the cert I think.

However... this can be closed now.

**Comment by Bubu** [comment]
I'm still using user_sql with out instance and some hardcoded groups_sql thing tacked onto it. But I really won't complain if someone else is maintainig it. At some point I might get around to submitting my changes to the now official fork. @andyboeh thanks for letting me know about this transfer :-).

**Comment by MariusBluem** [comment]
@Bubu Invited you into the repo :)

**Pull request closed without merging**
