### PR TITLE
Certificate for files_readmemd

### PR DESCRIPTION
**Pull request by mamatt**
Hi NC team 

Certificate request for files_readmeMD
-> https://gitlab.univ-nantes.fr/uncloud/files_readmemd

@MorrisJobke

### CODE REVIEW

**Comment by mamatt** [comment]
You were right it was missing some documentation/explanation  ;)
I've updated the readme file !

**Comment by jancborchardt** [comment]
@mamatt thanks a lot, cool! :)

One possible issue I could see is that "MarkDown editor need to be installed". We try not to have cross-app dependencies. But needs input from @rullzer @MorrisJobke how we handle this.

**Comment by mamatt** [comment]
The apps check that markdown editor is installed.
=> https://gitlab.univ-nantes.fr/uncloud/files_readmemd/blob/master/js/script.js#L30

**Comment by rullzer** [comment]
> @mamatt thanks a lot, cool! :)
> 
> One possible issue I could see is that "MarkDown editor need to be installed". We try not to have cross-app dependencies. But needs input from @rullzer @MorrisJobke how we handle this.

Fine I'd say. We do try to avoid it but here it is clear. And they check for it. :)

**Comment by mamatt** [comment]
For the next version, I'll try to switch from MD to raw sanitized txt if the MD editor app is not present.

**Pull request merged**
