### PR TITLE
Create holiday_calendars.csr

### PR DESCRIPTION
**Pull request by tcitworld**
Holiday calendars is an app listing links to public calendars representing the holidays and allowing to subscribe to them

Source: https://framagit.org/framasoft/nextcloud/holiday_calendars

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @tcitworld !

Only a suggestion:
rename your repository to holiday_calendars to maintain with the same name of app_id, this will make more easy to new developers to start working because only will necessary clone the repository inside the folder apps or custom_apps and start working.

I will wait for your opinion about this to follow with next steps.

**Comment by vitormattos** [comment]
@tcitworld can you put the csr file inside of folder with the same name of app_id? 

Example:

holiday_calendars/holiday_calendars.csr

**Comment by vitormattos** [comment]
To make clean the log, will be good amend to last commit

**Comment by tcitworld** [comment]
Fixed :see_no_evil:

**Comment by vitormattos** [comment]
All is ok.
Only suggestions:
* fill the readme with description of app
* add screenshots

**Comment by vitormattos** [comment]
Here: https://github.com/nextcloud/app-certificate-requests/commit/c01c82343c0b1e055aa5b56f18a17636f147d245

**Comment by vitormattos** [comment]
What do you think about to open an issue at `nextcloud/calendar` to suggest to migrate this feature to `nextcloud/calendar`?

**Comment by tcitworld** [comment]
Not really, this is a 3rd party app as intended.

https://github.com/nextcloud/calendar/issues/962

**Comment by Tealk** [comment]
where does the information about the holidays come from?

**Comment by nickvergessen** [comment]
Please ask in the repository of the app

**Pull request merged**
