### PR TITLE
Create ocjobs.csr

### PR DESCRIPTION
**Pull request by Lea9250**
@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@Lea9250 Is the app repo available somewhere?

**Comment by Lea9250** [comment]
Hi, here you go https://github.com/Lea9250/ocjobs

**Comment by MorrisJobke** [comment]
> Hi, here you go https://github.com/Lea9250/ocjobs

Thanks :) Keep in mind that you expose maybe sensitive information (like federated share IDs that are retried via a background job) via your API to all users of the instance (you have a "@NoAdminRequired" flag on that endpoint). 

But it's not our job to judge on this, so I will issue the cert for you.

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
84ac992

**Pull request merged**
