### PR TITLE
Create nextsign.csr

### PR DESCRIPTION
**Pull request by driverofthings**
An eSignature app for NextCloud.

@MorrisJobke

### CODE REVIEW

**Comment by juliushaertl** [comment]
Is the repo already available somewhere publicly?

**Comment by juliushaertl** [comment]
cc @blizzz

**Comment by blizzz** [comment]
@driverofthings what Julius said:

> Is the repo already available somewhere publicly?

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still relevant please reply :)

**Pull request closed without merging**
