### PR TITLE
Certificate signing request for Pax Fax, SMS Relentless and SIP Trip Phone

### PR DESCRIPTION
**Pull request by CoverTowerSuperAdmin**
These are 3 applications with completely different functions:

* Pax Fax is a Nextcloud application that allows sending and receiving faxes in Nextcloud.
It connects to a phaxio.com account and needs a phone number from Phaxio. We chose Phaxio as a FoIP provider solely for the quality of their services and low prices. We have no affiliation with Phaxio.
The git repository where the app is developed is [on our server](https://git.covertower.com/pax-fax/).

* SMS Relentless is a Nextcloud application that allows sending and receiving SMS messages in Nextcloud. It connects to a telnyx.com or plivo.com account and needs at least one phone number from one of the two providers. We have no affiliation with Telnyx or Plivo.
The git repository where the app is developed is [on our server](https://git.covertower.com/sms-relentless/).

* SIP Trip Phone is a Nextcloud application that acts like a browser phone. It connects to an Asterisk server to make and receive phone calls using SIP over WebSocket and WebRTC. For calls to and from regular phone numbers, a telnyx.com or localphone.com account is needed and a real phone number acquired from one of the two providers of SIP services. We have no affiliation with Telnyx or Localphone.
The git repository where the app is developed is [on our server](https://git.covertower.com/sip-trip-phone/).

Our [contact page](https://www.covertower.com/contact/).

### CODE REVIEW

**Comment by CoverTowerSuperAdmin** [comment]
@blizzz Can you issue a crt for this app, please ?

**Comment by CoverTowerSuperAdmin** [comment]
@rullzer  Can you please issue a crt file for this app ?

**Comment by nickvergessen** [comment]
@CoverTowerSuperAdmin  rullzer is not with the project anymore. Is he still mentioned in a manual/documentation?

**Comment by CoverTowerSuperAdmin** [comment]
Ok, then who is in charge with accepting these pull requests ? I need a crt file to be able to publish this app in the app store.

**Comment by nickvergessen** [comment]
The respective team should be subscribed to the repo and will respond as soon as their time permits

**Comment by CoverTowerSuperAdmin** [comment]
The README.md page of this repository specifies at point 5: "Nice to have: a link to the source code of the new app". This means that when we request a crt file for a new app, we can add a link to the source code of the app (which I did), but this is not an absolute requirement. This means that requesting a crt file for a new app is not the main stage in the app verification process. As can be deduced from [this guide](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#publishing-apps-on-the-app-store), a new app is thoroughly verified by Nextcloud after the crt file is issued and the app is registered, namely when the author attempts to upload an app release to the App Store. Am I right ?

**Comment by CoverTowerSuperAdmin** [comment]
If my deduction is right and this is not the main step in the app verification process, then, when can I expect to see these apps in the App Store ?

**Pull request closed without merging**
