### PR TITLE
Create dashboardcharts.csr

### PR DESCRIPTION
**Pull request by MarkPartlett**
Signed-off-by: MarkyMark_Qld mark@partlett.net

@MorrisJobke could you please sign request. https://github.com/MarkPartlett/dashboardcharts

### CODE REVIEW

**Comment by MarkPartlett** [comment]
@MorrisJobke can you please help?

**Comment by MarkPartlett** [comment]
@MorrisJobke can you please help?

**Comment by jospoortvliet** [comment]
Sorry it is taking so long, Morris and Roeland are both on holiday... Will ask who can do this now!

**Comment by blizzz** [comment]
Here you go https://github.com/nextcloud/app-certificate-requests/commit/a476c0c3b5c9b91cf72089a09ee084ea4e0d1f80  and thanks for your patience!

**Pull request merged**
