### PR TITLE
New app certificate request for spgverein

### PR DESCRIPTION
**Pull request by schrieveslaach**
As mentioned in #283 a lost my private key. Therefore, here is a new request.

### CODE REVIEW

**Comment by schrieveslaach** [comment]
@rullzer, could you help me here?

**Comment by MorrisJobke** [comment]
Let me revoke the old cert and create a new one.

**Comment by MorrisJobke** [comment]
352bda6

**Comment by MorrisJobke** [comment]
@schrieveslaach There was a problem on our side when the certificates were generated. There are a few certificates that have the same serial number. For now this is nothing to worry about, but once one certificate gets revoked all certificates with the same serial number won't work anymore. Thus I would ask you to take this new certificate for your app: b51f195. You key is still the same and the old certificate still works, but it might be that due to a revocation in the future the current one might be revoked as well. So please use the new one. Sorry for the inconvenience.

**Pull request merged**
