### PR TITLE
add uxcloud.csr

### PR DESCRIPTION
**Pull request by popyang**
add uxcloud.csr @MorrisJobke

### CODE REVIEW

**Comment by juliushaertl** [comment]
Do you have a link to the repository available?

**Comment by popyang** [comment]
> Do you have a link to the repository available?

Hello, I compiled the nextcloud desktop client, but it was blocked by antivirus software. The official client can be used normally. Is it because there is no code signing?

**Comment by popyang** [comment]
> > Do you have a link to the repository available?
> 
> Hello, I compiled the nextcloud desktop client, but it was blocked by antivirus software. The official client can be used normally. Is it because there is no code signing?

@juliushaertl

**Comment by ChristophWurst** [comment]
What is "uxcloud"?

**Comment by juliushaertl** [comment]
> Hello, I compiled the nextcloud desktop client, but it was blocked by antivirus software. The official client can be used normally. Is it because there is no code signing?

Maybe there was a misunderstanding then here. This repo is for requesting certificates for releasing apps to the Nextcloud app store, for code signing of the desktop client, please refer to your operating system documentation.

**Pull request closed without merging**
