### PR TITLE
Add wrikesync.csr

### PR DESCRIPTION
**Pull request by g-artech**
@MorrisJobke 
I appeal to you to accept this app. It synchronizes the folder structure of Wrike project management to Nextcloud and announces the members of Wrike if a file in a specific folder has been uploaded. 
Thank you in advance.

### CODE REVIEW

**Comment by blizzz** [comment]
@g-artech do you have a link to a repository?

**Comment by g-artech** [comment]
@blizzz 
Sure, give me a second.

**Comment by g-artech** [comment]
@blizzz 
You now have access to the repository:
https://github.com/g-artech/wrikesync

**Comment by blizzz** [comment]
Here you go: 5cf158980532bb5dcfcb703e17ac155c4cf4006d

**Comment by g-artech** [comment]
@blizzz 
Thanks! Can I now upload the app to the AppStore?

**Comment by blizzz** [comment]
> @blizzz
> Thanks! Can I now upload the app to the AppStore?

Yes, you can! If you need more info, follow https://nextcloudappstore.readthedocs.io/en/latest/developer.html#registering-an-app f.

**Comment by g-artech** [comment]
@blizzz 
I am getting the following error: "not a gzip file"
Link: https://g-ar.tech/downloads/wrikesync.tar.gz

**Comment by blizzz** [comment]
@g-artech the file looks good, and should not be problematic. Did you provide this exact link as download link?

**Comment by g-artech** [comment]
@blizzz 
Yes.

**Comment by g-artech** [comment]
@blizzz 
I still can't upload the app. The link is the same as provided in the comment. The signature was generated exactly as provided on the page.

**Comment by blizzz** [comment]
@g-artech did you register the app first?

**Comment by g-artech** [comment]
@blizzz 
Yes, i already registered the app but can't publish it.

**Comment by g-artech** [comment]
@blizzz 
I used the compress command before for taring the file. Now that I removed the parameter I am getting the following error: "wrikesync.tar.gz is not a valid tar.gz archive"

Do you have any idea what to do now?

**Comment by blizzz** [comment]
Now I also see the app in the DB, before it wasn't there.

Did you try to create the tarball with "make appstore"?

**Comment by g-artech** [comment]
No.
If I use this command, he will exclude my build folder and leave only the js folder instead.

However, this is not possible because the React frontend is in the build folder.

**Comment by blizzz** [comment]
customize it to your needs https://github.com/g-artech/wrikesync/blob/master/Makefile#L127-L150

**Comment by g-artech** [comment]
@blizzz
Is it possible for you to help me upload the file in your appstore (without Makefile)?

**Comment by g-artech** [comment]
@blizzz 
I have now tried several times to compress the app with different methods and then upload it, but I get the same error every time. 
The command is correct, isn't it?

`tar -cf wrikesync.tar.gz wrikesync/`

**Comment by g-artech** [comment]
@blizzz 
I tried to use the Makefile now but I am still getting the same error.

@MorrisJobke 
Is this error familiar to you or am I doing something wrong?

**Comment by blizzz** [comment]
@g-artech do you still get the same error message?

**Comment by g-artech** [comment]
Yes.

**Comment by g-artech** [comment]
@blizzz 
Maybe you know where this error comes from?

**Comment by blizzz** [comment]
Sure… from a python module that validates the archive. But i do not see this message appearing in the logs now.

**Comment by g-artech** [comment]
Is it possible for you to come to my zoom-meeting?

**Comment by blizzz** [comment]
For the record, the appstore was having issues with downloading the file correctly from the original server.

**Comment by g-artech** [comment]
I forgot to reopen the repository again after our call.

**Comment by andyzimmerer** [comment]
-

**Pull request merged**
