### PR TITLE
Create money.csr

### PR DESCRIPTION
**Pull request by powerpaul17**
Thank you @LukasReschke :)

### CODE REVIEW

**Comment by LukasReschke** [comment]
Is there already a working app somewhere with screenshots or so? :)

**Comment by MariusBluem** [comment]
https://github.com/powerpaul17/nc_money ... Not tested, but this seems to be the repo 😁 @LukasReschke

**Comment by powerpaul17** [comment]
Yes this is indeed the repo. The basic functionality is working but there are still lots of things to fix and improve. I was planning to release an alpha version to see if there are more people interested..

**Comment by LukasReschke** [comment]
The info.xml doesn't seem to validate: https://github.com/powerpaul17/nc_money/blob/278ba25b4591bf34264d4029c2aa162248c3d882/appinfo/info.xml#L23

**Comment by MariusBluem** [comment]
https://github.com/powerpaul17/nc_money/pull/1 will fix this 😉

**Comment by powerpaul17** [comment]
@LukasReschke Yes, sorry, I forgot to add the actual screenshot file in the xml.

@MariusBluem Thanks for the pull request, but it wasn't a really hard fix to do.. :)

**Comment by LukasReschke** [comment]
I've issued a certificate for the app. Please make sure to communicate this as alpha release in the appstore description :)

**Comment by LukasReschke** [comment]
Certificate at https://github.com/nextcloud/app-certificate-requests/blob/ccfdb8645ce9e1204cd4bbdd99d81f7f0c3e0d10/money/money.crt

**Comment by powerpaul17** [comment]
Thank you @LukasReschke

**Pull request merged**
