### PR TITLE
Update spgverein.crt

### PR DESCRIPTION
**Pull request by schrieveslaach**
Somehow the verification of spgverein fails (see [here](https://gitlab.com/schrieveslaach/nextcloud-spgverein-app/issues/2)). As proposed [here](https://github.com/nextcloud/app-certificate-requests/pull/60#issuecomment-530276121) the simplest solution would be to recreate the certificate.

### CODE REVIEW

**Comment by rullzer** [comment]
I'll take care of this tomorrow

**Comment by rullzer** [comment]
See https://github.com/nextcloud/app-certificate-requests/blob/master/spgverein/spgverein.crt

**Comment by mburnicki** [comment]
Hi, I just came across the message that the certificate of the app was invalid when I tried to install it on NC 17.0.2 from the app store.

Does the new cert need to be published or pushed to the store, or is the new cert still considered invalid?

**Comment by schrieveslaach** [comment]
@mburnicki, I made a very stupid mistake. I lost my certificate key. I have to make a new PR and the I will upload a signed version of the plugin. @rullzer, I'm very sorry, about that.

**Pull request merged**
