### PR TITLE
Create appsautoupdater.csr

### PR DESCRIPTION
**Pull request by Adphi**
@MorrisJobke

source code (alpha) : https://git.adphi.net/Adphi/AppsAutoUpdater

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer @ChristophWurst Regarding the apps purpose.

In general I'm fine with this and if somebody wants to install this I'm fine too. Just want your opinion on this.

**Comment by nickvergessen** [comment]
Fine by me

**Comment by MorrisJobke** [comment]
e0c652b

**Comment by nickvergessen** [comment]
@Adphi we would also accept a Pull Request to the server for this on master.

2 Options should be added:
1. allow to disable it
2. allow to specify at which time this is allowed (so e.g. calls that are done with Talk in the office hours are not interrupted.

If you need help on implementing those changes, just send your PR without it and we can take care of it.

**Comment by Adphi** [comment]
Thank you. The two options are planned. (I just need to find the time to do it)

**Comment by MorrisJobke** [comment]
> Thank you. The two options are planned. (I just need to find the time to do it)

It's also fine to add the background job for now and then enhance this step by step inside the server repository :)

**Pull request merged**
