### PR TITLE
Certificate for new maintainer of Sharerenamer

### PR DESCRIPTION
**Pull request by JonathanTreffler**
As described in https://github.com/JonathanTreffler/sharerenamer/issues/29 @DecaTec cannot maintain the Sharerenamer App anymore.
I took over the development and rewrote that app.
Now I want to create a release on the appstore and need a new certificate for that.

### CODE REVIEW

**Comment by vitormattos** [comment]
055cfad4eb51cf67572dcce50ce2b31b8a3f154e

**Comment by blizzz** [comment]
@JonathanTreffler i guess we need to move the app to you on the appstore as well. What is your username there?

**Comment by JonathanTreffler** [comment]
> @JonathanTreffler i guess we need to move the app to you on the appstore as well. What is your username there?

Yes, that is correct. My username on the appstore is TessyPowder and my email address there is mail@jonathan-treffler.de .

**Comment by blizzz** [comment]
@JonathanTreffler thanks! The app data is updated accordingly!

**Comment by JonathanTreffler** [comment]
@blizzz Thanks :)
Transferring the ownership worked.

Do I understand correctly, that all previous releases got removed from the app store, because of the key change ?
If that is the case am I assuming correctly that uploading my first new release works simply using the "App-Veröffentlichung hochladen" page?

**Comment by blizzz** [comment]
Old releases were not removed (also the crl is shipped with the next NC versions), but yes, you can just (re-)upload releases.

**Pull request merged**
