### PR TITLE
Create cfg_share_links.csr

### PR DESCRIPTION
**Pull request by jimmyl0l3c**
https://github.com/jimmyl0l3c/cfg_share_links

### CODE REVIEW

**Comment by nickvergessen** [comment]
Might want to join forces with https://github.com/nextcloud/app-certificate-requests/pull/478 ?

**Comment by jimmyl0l3c** [comment]
I'm not sure about joining with sharerenamer. With all due respect, but I dont like sharerenamer's approach and I would like to keep my app as an alternative to sharerenamer, if that's possible. (Differences can be seen in the screenshots I added to readme recently)
And I'm sorry for the delayed reply.

**Comment by vitormattos** [comment]
Hi @jimmyl0l3c
can you fix this?
https://github.com/nextcloud/app-certificate-requests/pull/484/checks?check_run_id=5188866172

**Comment by vitormattos** [comment]
@jimmyl0l3c 
Suggestions:
rename your repository from cfg-share-links to cfgsharelinks
OR: rename your repository from cfg-share-links to cfg_share_links and change the app_id to cfg_share_links
Motivation: Make more easy to new developers clone the repository and start to work without necessity to rename the repository folder to same name of app_id

Only a suggestion, waiting for your opinion to go ahead.

**Comment by vitormattos** [comment]
Yes, you will need generate a new certificate. Isn't a problem now because we don't merged your certificate to app certificate repository.

**Comment by jimmyl0l3c** [comment]
App_id is changed, repo renamed and I comitted new certificate.

**Comment by vitormattos** [comment]
Beautiful! Can you squash all into only one commit?

**Comment by vitormattos** [comment]
crt here: https://github.com/nextcloud/app-certificate-requests/commit/d2a4ca6755d275384a4ba94d8d6b23bc7fe0e6c1

**Comment by jimmyl0l3c** [comment]
Thank you

**Pull request merged**
