### PR TITLE
Create aboutinfo.csr

### PR DESCRIPTION
**Pull request by galgenjunge**
Private

### CODE REVIEW

**Comment by LukasReschke** [comment]
Thanks for your pull request, is your app available somewhere? Certificates are only issued for maintained, functioning apps. Note that you don't need a certificate to use an app for yourself, but just to upload it to the app store.

**Comment by galgenjunge** [comment]
This app is just for contact information from me.
The Nextcloud say this Error:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
Results
=======
- about
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

**Comment by BernhardPosselt** [comment]
Did you ever have a valid certificate?

**Comment by galgenjunge** [comment]
No, but he has previously complained that he could not make a comparison. Now he does not complain any more today had an update for Nextcloud.

**Pull request closed without merging**
