### PR TITLE
Update files_external_dropbox.csr

### PR DESCRIPTION
**Pull request by DJaeger**
@MorrisJobke

Sources: https://github.com/DJaeger/files_external_dropbox

As the upstream repo seems to be not maintained anymore and the app was never published to the appstore I request to replace the never used certs by my new keys to publish my updated fork.

### CODE REVIEW

**Comment by DJaeger** [comment]
This is the first part to fulfill https://github.com/icewind1991/files_external_dropbox/issues/20
I hope this comment doesn't lead Github to automatically close that issue after merging

**Comment by MorrisJobke** [comment]
Asking the original maintainer for this - maybe @icewind1991 can also hand over the cert to you.

Ref #95

**Comment by DJaeger** [comment]
Thx for approving @icewind1991

**Comment by MorrisJobke** [comment]
7c5435c

**Pull request merged**
