### PR TITLE
Create syncblue.csr

### PR DESCRIPTION
**Pull request by sync-blue**
Please verify our CSR.

Required for our integration of [sync.blue](https://www.sync.blue/) and Nextcloud.
This will enable countless of [Nextcloud integrations](https://info.sync.blue/app/nextcloud/en/).

Many thanks in.advance.

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @sync-blue !
Can you share the link with the app source code?
You also need check the tests:
https://github.com/nextcloud/app-certificate-requests/pull/506/checks?check_run_id=5461269527

**Comment by vitormattos** [comment]
ping @sync-blue

**Comment by sync-blue** [comment]
ping @vitormattos

**Comment by vitormattos** [comment]
Here: d12cd2936388ab812565f4e4a8d6dcf8cbb6a894

**Pull request merged**
