### PR TITLE
Request cert for integration_jupyterhub

### PR DESCRIPTION
**Pull request by mickenordin**
This is a request for a certificate for an integration app for jupyterhub: https://jupyter.org/hub

### Checklist

- Please include a link to your app repository
* https://github.com/SUNET/nextcloud-jupyter

### CODE REVIEW

**Review by mgallien — CHANGES_REQUESTED** [review]
@mickenordin there is a typo in the name of the csr file `integration_jupyterhub/intergration_jupyterhub.csr`

**Comment by mickenordin** [comment]
> @mickenordin there is a typo in the name of the csr file `integration_jupyterhub/intergration_jupyterhub.csr`

Sorry about that @mgallien should be fixed now!

**Comment by mgallien** [comment]
@mickenordin no worries
you can find it here adeb28e0aebe8391654eba4f38f1d106b04d6981

**Comment by mickenordin** [comment]
Something seems strange here I am trying to register my app, but I get:

`Signature is invalid: [('rsa routines', '', 'bad signature'), ('Provider routines', '', 'RSA lib')]`

from the appstore web interface, did I make a misstake or is it the wrong cert?

**Comment by mickenordin** [comment]
modulus of the csr and the key is
`MD5(stdin)= d41d8cd98f00b204e9800998ecf8427e`
While modulus of the crt is 
`MD5(stdin)= c5658e73472b650911e4b3c88d0c8d8a`
This indicates that I got someone elses cert :)

**Comment by mickenordin** [comment]
My misstake:

` ``
micke@minis  ~  openssl x509 -noout -modulus -in .nextcloud/certificates/integration_jupyterhub.crt | openssl md5 
MD5(stdin)= c5658e73472b650911e4b3c88d0c8d8a
 micke@minis  ~  openssl rsa -noout -modulus -in .nextcloud/certificates/integration_jupyterhub.key | openssl md5
MD5(stdin)= c5658e73472b650911e4b3c88d0c8d8a
 micke@minis  ~  openssl req -noout -modulus -in .nextcloud/certificates/integration_jupyterhub.csr | openssl md5
MD5(stdin)= c5658e73472b650911e4b3c88d0c8d8a
```

**Pull request merged**
