### PR TITLE
Add twofactor-webauthn certificate

### PR DESCRIPTION
**Pull request by michib**
Signed-off-by: Michael <M.Flower@gmx.de>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
JFYI @rullzer @ChristophWurst 


Repo at https://github.com/michib/nextcloud_twofactor_webauthn

**Comment by ChristophWurst** [comment]
> Repo at https://github.com/michib/nextcloud_twofactor_webauthn

It's the skeleton from apps.nextcloud.com. No code there yet :man_shrugging:

**Comment by MorrisJobke** [comment]
> It's the skeleton from apps.nextcloud.com. No code there yet 🤷‍♂

Just want to highlight about the project in general :)

**Comment by MorrisJobke** [comment]
05c9d21

**Comment by michib** [comment]
The working code is in the branch feature/first-auth.

Didn't merge it into master, because the credits in the files and tests are still missing.

But it's possible to use webauthn 2fa with the code

**Comment by rullzer** [comment]
@michib feel free to join us on IRC. I've also been looking into webauthn (for passwordless auth but still) so would be interested to hear what you think about that.

**Pull request merged**
