### PR TITLE
Add integration_documenso.crt

### PR DESCRIPTION
**Pull request by janepie**
Source URL: https://github.com/janepie/integration_documenso

### CODE REVIEW

**Comment by DaphneMuller** [comment]
@GretaD any chance you can approve this one today?

**Comment by GretaD** [comment]
yes, of course, sorry i was on sick leave

**Comment by GretaD** [comment]
@janepie there is an issue with your pr.

there is 2 parent folders for the csr file
integration_documenso/integration/documenso.csr
it should be
integration_documenso/integration_documenso.csr

please change it and i will generate the certificate

**Comment by GretaD** [comment]
thanks a lot Jana, heres the certificate 1400707aa2d47d7d0dcac24f7e5ec977902456bc

**Pull request merged**
