### PR TITLE
Create rocketchat.csr

### PR DESCRIPTION
**Pull request by engelgabriel**
Signed-off-by: Gabriel Engel <gabriel.engel@rocket.chat>

### CODE REVIEW

**Comment by engelgabriel** [comment]
This is the source code, I am trying to publish the official Rocket Chat App
https://github.com/RocketChat/NextCloud

**Comment by nickvergessen** [comment]
So this or https://github.com/nextcloud/app-certificate-requests/pull/492 ?

**Comment by engelgabriel** [comment]
This please

**Comment by vitormattos** [comment]
Hi @engelgabriel (ou, olá Gabriel)

You can find the certificate here https://github.com/nextcloud/app-certificate-requests/commit/1af63b5394e73217193c461fa349ff96d994716a

**Comment by vitormattos** [comment]
Your PR was merged here https://github.com/nextcloud/app-certificate-requests/commit/b4c6d89f8c00890f89a6a0c9fd9e8606a8718ad1
I amended a small change to your commti to fix the path.

**Comment by ruvenss** [comment]
@vitormattos I have this message when registering the app : `Signature is invalid: Incorrect padding`

**Pull request closed without merging**
