### PR TITLE
update vdirsyncerui.csr

### PR DESCRIPTION
**Pull request by doganoo**
Signed-off-by: Doğan Uçar <dogan@dogan-ucar.de>

Hey. I lost my certificates and keys so I need to recreate the csr. Thanks in advance for your support.

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @doganoo,
Can you share the repository URL and, if published, the URL of this app on apps.nextcloud.com?

**Comment by doganoo** [comment]
the app is not published on the App Store yet. The repo is located here: https://github.com/Ucar-Solutions/vdirsyncerui

**Comment by vitormattos** [comment]
original request https://github.com/nextcloud/app-certificate-requests/pull/508

**Comment by vitormattos** [comment]
The previous comment was only to associate with the previous cert request and maintain the PR history.

I finished the revoke and generation of your new crt.
You can get the new here: https://github.com/nextcloud/app-certificate-requests/commit/ee4093b1b881193d9cfa0b3fe823c67587bbd637

Save your data on a password manager. By example, I use KeePassXC to do this at my desktop environment.
You also can store in your Nextcloud instance.

Will make more easy your work if you store your .crt, .csr and .key files. The .crt you can get here.

Good coding for you.
May the Open Source force be with you!

**Pull request merged**
