### PR TITLE
Add CSR for certificate24 app.

### PR DESCRIPTION
**Pull request by fancycode**
App source code is available at
https://github.com/astrairidium/nextcloud-certificate24

This more or less replaces #616 as we had a last-minute change of the app id :-/ Sorry about the noise.

### CODE REVIEW

**Comment by mgallien** [comment]
@fancycode can you also remove the no longer needed csr and certificate in this PR ?

**Comment by fancycode** [comment]
> @fancycode can you also remove the no longer needed csr and certificate in this PR ?

Done

**Review by mgallien — APPROVED** [review]

**Review by mgallien — APPROVED** [review]

**Comment by mgallien** [comment]
you can find the new certificate here c74e8c54325ee3d1e7ed4c492003f96d51abdea6

**Comment by fancycode** [comment]
> you can find the new certificate here [c74e8c5](https://github.com/nextcloud/app-certificate-requests/commit/c74e8c54325ee3d1e7ed4c492003f96d51abdea6)

Thanks!

**Pull request merged**
