### PR TITLE
duplicatefinder request

### PR DESCRIPTION
**Pull request by eldertek**
### Checklist

Hello ! 
https://github.com/PaulLereverend/NextcloudDuplicateFinder is not maintained anymore, there are issues when installing or trying to use the app.

I wanna be a maintainer of this app. I tested my version on 3 last Nextcloud versions.

Here is my repository : https://github.com/eldertek/NextcloudDuplicateFinder

I tried to contact the original maintainer, without succeeding.

My email address: andrelauret@eclipse-technology.eu

### CODE REVIEW

**Comment by mgallien** [comment]
@eldertek the DCO check is failing and please do not remove the existing certificate as we would revoke it and replace it once the PR can be merged
could you create (unless there is already one) an issue in upstream repository and ping the author of the application requesting the take over (maybe even link this PR in your issue) ?
I will also try to send an email to the original author myself

**Comment by eldertek** [comment]
@mgallien any news ?

**Comment by mgallien** [comment]
@eldertek I have not got any reply yet

**Comment by eldertek** [comment]
> @eldertek I have not got any reply yet

It's been two weeks I have opened issue on up, I'm not sure we will got any reply...

**Review by mgallien — CHANGES_REQUESTED** [review]
@eldertek sorry to have miss that before
you need to override the old certificate (`duplicatefinder/duplicatefinder.csr`)
then it is easier for us to track that the previous one was revoked and replaced

**Comment by eldertek** [comment]
Sorry but I don't understand what you want 😅

**Comment by mgallien** [comment]
> Sorry but I don't understand what you want sweat_smile

yes please put the new certificate under this name `duplicatefinder/duplicatefinder.csr`

**Comment by eldertek** [comment]
You told me to not do this in previous message ?
"please do not remove the existing certificate as we would revoke it and replace it once the PR can be merged"

**Comment by mgallien** [comment]
> You told me to not do this in previous message ? "please do not remove the existing certificate as we would revoke it and replace it once the PR can be merged"

@eldertek I am talking about the csr certificate signing request, not the certificate itself

**Comment by eldertek** [comment]
I just need to rename duplicatefinder/duplicatefinder_new.csr to duplicatefinder/duplicatefinder.csr 

That's right ?

Very sorry I am french and right now I don't understand your request..

**Comment by mgallien** [comment]
> I just need to rename duplicatefinder/duplicatefinder_new.csr to duplicatefinder/duplicatefinder.csr
> 
> That's right ?
> 
> Very sorry I am french and right now I don't understand your request..

@eldertek yes

**Comment by eldertek** [comment]
Should be okay @mgallien

**Comment by mgallien** [comment]
please find it here 99713c4fba975cbd7c54d3afa03d6636ed408bb2

**Comment by eldertek** [comment]
@mgallien I got that on the register page :
Only the app owner is allowed to update the certificate

**Comment by Nightad** [comment]
> @mgallien I got that on the register page : Only the app owner is allowed to update the certificate

I really hope it could be solved easily and quickly, because the app is great and right now it doesn't work anymore!

**Comment by Nightad** [comment]
> @mgallien I got that on the register page :
> Only the app owner is allowed to update the certificate

Any news?

**Comment by nickvergessen** [comment]
What's your appstore account name @eldertek

**Comment by eldertek** [comment]
Username : eldertek 
Mail : andrelauret@eclipse-technology.eu

**Comment by nickvergessen** [comment]
Modified: https://apps.nextcloud.com/apps/duplicatefinder

**Pull request merged**
