### PR TITLE
add integration_restyacore.csr

### PR DESCRIPTION
**Pull request by sridhar391**
Restya Core integration (dashboard widget, Activity notifications)

### CODE REVIEW

**Comment by sridhar391** [comment]
> OK! And it does not make sense to provide both dashboard widgets in one app?

We have developed two different products named Restyaboard and Restya Core and Restya Core is a new product which is completely different from Restyaboard product, and we have only developed Nextcloud integration for Restyaboard and now we have developed Nextcloud integration for Restya Core

**Comment by sridhar391** [comment]
> > OK! And it does not make sense to provide both dashboard widgets in one app?
> 
> We have developed two different products named Restyaboard and Restya Core and Restya Core is a new product which is completely different from Restyaboard product, and we have only developed Nextcloud integration for Restyaboard and now we have developed Nextcloud integration for Restya Core

Please accept the pull request

**Comment by sridhar391** [comment]
> > > OK! And it does not make sense to provide both dashboard widgets in one app?
> > 
> > 
> > We have developed two different products named Restyaboard and Restya Core and Restya Core is a new product which is completely different from Restyaboard product, and we have only developed Nextcloud integration for Restyaboard and now we have developed Nextcloud integration for Restya Core
> 
> Please accept the pull request

Please accept the pull request as some of users are expecting the Restya Core nextcloud integration

**Comment by sridhar391** [comment]
> Please accept the pull request as some of users are expecting the Restya Core nextcloud integration

@blizzz   Please accept the pull request as some of users are expecting the Restya Core nextcloud integration

**Comment by sridhar391** [comment]
> OK! And it does not make sense to provide both dashboard widgets in one app?

> We have developed two different products named Restyaboard and Restya Core and Restya Core is a new product which is completely different from Restyaboard product, and we have only developed Nextcloud integration for Restyaboard and now we have developed Nextcloud integration for Restya Core

> Please accept the pull request

@blizzz   Please accept the pull request as some of users are expecting the Restya Core nextcloud integration

**Comment by blizzz** [comment]
@sridhar391 sorry for the delay. we are increasing the team for issuing app certs to avoid so long waiting times and will deal with your request today.

**Comment by blizzz** [comment]
eb1f86b5f88e9fb458f03c87b033009889acb86a

**Pull request merged**
