### PR TITLE
certificate for user_external

### PR DESCRIPTION
**Pull request by violoncelloCH**
certificate for the user_external app to publish it to the appstore and make it independent from server releases
cc @nextcloud/user_external @jancborchardt 
for nextcloud/user_external#22 

Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

### CODE REVIEW

**Comment by jancborchardt** [comment]
@MariusBluem mentioned that the app is marked as official/shipped and should maybe have "Nextcloud" as a publisher?

@rullzer @MorrisJobke what's your call?

**Comment by rullzer** [comment]
> @MariusBluem mentioned that the app is marked as official/shipped and should maybe have "Nextcloud" as a publisher?
> 
> @rullzer @MorrisJobke what's your call?

Doesn't matter much IMO.

**Comment by rullzer** [comment]
So. I'm a bit hessitant. In the past we have had issues with apps that were both shipped and in the appstore when upgrading.

**Comment by MariusBluem** [comment]
We could remove the shipped-flag and remove it from the build script with 15.0.1. Minimal compatible version would be 15, all other old releases will not be affected.
Its not working with 15.0.0 at all in the current release so we would at least not break something ...

**Comment by violoncelloCH** [comment]
> @MariusBluem mentioned that the app is marked as official/shipped and should maybe have "Nextcloud" as a publisher?

how could I achieve this? can I just set "Nextcloud" as `<author>`?

I already thought I'll have to remove the shipped-flag. see PR nextcloud/user_external#26

**Comment by MorrisJobke** [comment]
> how could I achieve this? can I just set "Nextcloud" as `<author>`?

That is only defined in the app store.

**Pull request merged**
