### PR TITLE
Create collectives.csr

### PR DESCRIPTION
**Pull request by mejo-**
This CSR is meant for our new Collectives app: https://gitlab.com/collectivecloud/collectives

@MorrisJobke

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
For the record, the correct GitLab link is: https://gitlab.com/collectivecloud/collectives ;)

**Comment by mejo-** [comment]
@jancborchardt you're absolutely right. I miss-typed the URL without double-checking - should have used copy & paste instead :wink: Fixed now in the commit message.

Is anything missing from getting this CSR accepted?

**Comment by nickvergessen** [comment]
The main person for this is currently on vacation.

Cc @rullzer

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
@mejo- see https://github.com/nextcloud/app-certificate-requests/blob/master/collectives/collectives.crt

**Comment by mejo-** [comment]
Yay, thanks a lot :heart:

**Pull request merged**
