### PR TITLE
Add fileslibreofficeedit cert

### PR DESCRIPTION
**Pull request by smehrbrodt**

### CODE REVIEW

**Comment by blizzz** [comment]
Would you have a link to the sources?

**Comment by smehrbrodt** [comment]
> Would you have a link to the sources?

Sure: https://github.com/allotropia/nextcloud_files_libreoffice_edit

**Comment by smehrbrodt** [comment]
Anything else missing?

**Comment by blizzz** [comment]
Thanks, that's all! Here you go: 6c1469013852a1e3527a8ad4822c91506b3a7ea9

**Pull request merged**
