### PR TITLE
add registertocontact

### PR DESCRIPTION
**Pull request by doganoo**
Signed-off-by: Dogan Ucar <info@ucar-solutions.de>

### Checklist

- [Please include a link to your app repository](https://github.com/Ucar-Solutions/nc-register-2-contact)

### CODE REVIEW

**Comment by doganoo** [comment]
sorry, I do not get why checks fail. Can you please help me?

**Comment by nickvergessen** [comment]
You need to sign-off your commit

**Comment by doganoo** [comment]
@nickvergessen 
that's what I tried

**Comment by doganoo** [comment]
@nickvergessen 
please check my commit, I already did this:

image

do I need to remove "add registertocontact"?

**Comment by nickvergessen** [comment]
If you click on the dco and then scroll to the summary at the end, it shows another email address as expected. But i guess this is fine

**Comment by doganoo** [comment]
meaning what? we can merge? or should I create a new PR?

**Comment by nickvergessen** [comment]
You can adjust your email in that message, or the person in charge accepts it with a different one.

They will let you know

**Comment by mgallien** [comment]
@doganoo indeed, I would like to be sure before I would generate the certificate for your request
do you really intend this info to be correct ?
DCO check is reporting:
`Author: Doğan Uçar, Committer: Doğan Uçar; Expected "Doğan Uçar [dogan@dogan-ucar.de](mailto:dogan@dogan-ucar.de)", but got "Dogan Ucar [info@ucar-solutions.de](mailto:info@ucar-solutions.de)"`
so do you really expect to sign your commit with this email `info@ucar-solutions.de` ?
I am fine accepting your request since it is signed

**Comment by doganoo** [comment]
@mgallien 
yes this is ok for me so please proceed

**Comment by mgallien** [comment]
@doganoo next time, if you want to avoid having to reply to questions, setup your account to have the email address you use to sign your commits (and you can put several different email addresses)
you can find the certificate here cc1f27324cd3feb2063972e1f2be7c37612cf471

**Comment by doganoo** [comment]
@mgallien
nothing to report here?

where to report this as it seems like a bug on your side.

**Comment by mgallien** [comment]
@doganoo 
I do not have enough knowledge to help you on this
the best is to reach out to other developers working on Nextcloud app
you can use the community Talk room for that
https://cloud.nextcloud.com/call/xs25tz5y

**Pull request merged**
