### PR TITLE
EmlViewer.csr

### PR DESCRIPTION
**Pull request by a11exandru**
Add EmlViewer.csr

### CODE REVIEW

**Comment by a11exandru** [comment]
@MorrisJobke

**Comment by rullzer** [comment]
There you go

https://github.com/nextcloud/app-certificate-requests/blob/master/emlviwer/EmlViewer.crt

**Comment by a11exandru** [comment]
Thanks, but i can't upload the app release because i generate the request certificate for "EmlViewer.csr" instead of "emlviewer.csr", and if i try to upload this i get the error of "App emlviewer does not exist, you need to registerit first".
@rullzer It's ok to regenerate the certificate? Or exists other solution to solve that? 
And i'm really sorry for that!

**Comment by a11exandru** [comment]
If the best solution is to generate a new certificate, there is the new PR: https://github.com/nextcloud/app-certificate-requests/pull/280 .

**Comment by rullzer** [comment]
Yeah a new certificate. All lowercase.

**Comment by a11exandru** [comment]
Ok, here is the link: https://github.com/nextcloud/app-certificate-requests/pull/280

**Pull request merged**
