### PR TITLE
Update lost certificate for integration_homeassistant

### PR DESCRIPTION
**Pull request by poulou0**
Hello, just realized that I naively lost my previous certificate after wiping my computer 🙈

My app is https://github.com/poulou0/nextcloud-homeassistant-integration

Thank you

### CODE REVIEW

**Comment by mgallien** [comment]
hello @poulou0 
can you fix the failing DCO check ? see https://github.com/nextcloud/app-certificate-requests/pull/667/checks?check_run_id=20049683243

**Comment by poulou0** [comment]
Done :))

**Comment by mgallien** [comment]
@poulou0 You can find the new certificate here 8a70ce9b6692ede30c5f49d7c4c098400c641ef2

**Comment by poulou0** [comment]
Hello there, this certificate has been revoked. What is the reason and should I create a new one to fix it? @mgallien

**Pull request merged**
