### PR TITLE
Create pdf_tailor.csr

### PR DESCRIPTION
**Pull request by janis91**
https://github.com/janis91/pdf_tailor
(status: starting)

@MorrisJobke 

Thank you :-)

### CODE REVIEW

**Comment by janis91** [comment]
See branch "init" for app code.

**Comment by janis91** [comment]
@juliushaertl I also @ you, because I am not sure about Morris, if he is still active. btw: Do you know who I should ask about setting up transifex for my new app? Thank you :-)

**Comment by juliushaertl** [comment]
@janis91 I've created https://github.com/nextcloud/docker-ci/pull/202 for that. Could you make sure that your .tx directory is available in the master branch, since otherwise that sync would fail.

**Comment by blizzz** [comment]
@janis91 1e43d71be5d52961a6da0d5a526d171250a1058b

**Comment by juliushaertl** [comment]
@janis91 Transifex is also running fine now https://github.com/janis91/pdf_tailor/commit/b42a113aa4ab97a0d37f9793bcd778553d3e2ae0

**Pull request merged**
