### PR TITLE
Added files_photospheres pkey

### PR DESCRIPTION
**Pull request by SudoHenk**
Project page: https://gitlab.maikel.pro/maikeldus/nextcloud-photospheres

### CODE REVIEW

**Comment by SudoHenk** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
@SudoHenk Mind to maybe work together with @R0Wi, because there is a similar app as well: https://github.com/R0Wi/Nextcloud-PhotoSphereViewer

**Comment by MorrisJobke** [comment]
Cert is at 5f131a7

**Comment by SudoHenk** [comment]
@R0Wi It looks like we've got an almost identical app. I've had a quick look and it looks like mine has 2 things done differently:

* It will use XMP exit data to determine which viewer to use.
* If you share a file it will also use the photo sphere viewer, if possible.

I'm okay with merging these two points into your viewer, if you're okay with that?

**Comment by MorrisJobke** [comment]
> I'm okay with merging these two points into your viewer, if you're okay with that?

It's also fine to merge both somehow :) Just want to join you two so that you can both keep the nice work you did up and running 😃

**Comment by R0Wi** [comment]
Hey guys, i think merging would be great. There's a lot of stuff left we can do and implement.

@SudoHenk i'll have a closer look at your app tomorrow, then we can think about how merging could be done :-)

**Comment by R0Wi** [comment]
@SudoHenk thats funny, we had almost the same ideas. I think we can get the app much better if we collaborate. Shall we discuss a plan here or via PM?

**Comment by nickvergessen** [comment]
We can also move one of the apps to the nextcloud/ organisation on github, if you want that.

Just send me an email to `<my github name>@nextcloud.com`

**Comment by R0Wi** [comment]
Thats also a nice idea. So maybe we would start with an empty repo and merge the apps there?

**Comment by SudoHenk** [comment]
A repo under nextcloud would be nice! I think its best to grab @R0Wi viewer (as the code is cleaner) and in the weekend I can merge the changes from mine into it.

**Comment by MorrisJobke** [comment]
> A repo under nextcloud would be nice! I think its best to grab @R0Wi viewer (as the code is cleaner) and in the weekend I can merge the changes from mine into it.

To which name do you want to stick?

**Comment by SudoHenk** [comment]
`files_photospheres` would best fit the current naming convention of Nextcloud, do you agree @R0Wi ?

**Comment by nickvergessen** [comment]
In this case grant @MorrisJobke or me admin priviledges and we can move it (including the existing issues, branches and PRs) to Nextcloud.

**Comment by R0Wi** [comment]
That's a cool idea. I'm ok with the naming (since i didn't know the nextcloud conventions). So i'll give you both admin rights.

**Comment by MorrisJobke** [comment]
> That's a cool idea. I'm ok with the naming (since i didn't know the nextcloud conventions). So i'll give you both admin rights.

Ah - right. Github does not allow to give other people admin rights for your own repos. Let me then just create a repository and move the git history. As there are not too much tickets in the repo.

**Comment by MorrisJobke** [comment]
There it is: https://github.com/nextcloud/files_photospheres

I invited both of you to the community :)

I also locked the master branch to be protected - so it's can't be overwritten.

**Comment by MorrisJobke** [comment]
I will also add a transifex sync job to the repo so that the app is automatically translated by our translators community :)

**Comment by R0Wi** [comment]
Nice work, thank you @MorrisJobke . Just one question: you've just moved @SudoHenk 's repo. His suggestion was to move my repo and then he would merge his changes. Is it ok to clear the repo and start with mine again?

**Comment by MorrisJobke** [comment]
> Nice work, thank you @MorrisJobke . Just one question: you've just moved @SudoHenk 's repo. His suggestion was to move my repo and then he would merge his changes. Is it ok to clear the repo and start with mine again?

Sure xD Then I mixed that up ... let's do it again.

**Comment by MorrisJobke** [comment]
Done - keep in mind to update the appid and update all the `OCA\...` namespaces to this one then.

**Comment by R0Wi** [comment]
Thanks, i'll keep that in mind :-)

**Comment by R0Wi** [comment]
@SudoHenk i have changed the namespaces and stuff so now you could start merging your changes if you like. I'm currently working on a serverside-feature, which will allow to get only the xmp-data of a file so don't investigate to much time merging the "is it a pano-image?"-stuff.

@MorrisJobke if we would like to push the app to the nextcloud-store, how can we achieve this?

**Comment by MorrisJobke** [comment]
As this is a new app ID just upload it to the AppStore with the signature of the archive. The signature needs to be generated by @sudohenk (or @sudohenk provides you with the key, then you can also do it). Additionally we can add you both as maintainers of the app.

**Comment by R0Wi** [comment]
@MorrisJobke thanks for the response. Let's wait until merging is done and the app is tested properly. Then we could publish it and of course it would be nice to become maintainers :-)

**Comment by SudoHenk** [comment]
@R0Wi good idea to do this server side! I've been tinkering with it Saturday but I noticed that checking the xmp tags client side is just too sluggish on slow internet connections.

I will probably commit the changes from mine this evening or tomorrow. About the pkey, should I e-mail it to you?

**Comment by R0Wi** [comment]
@SudoHenk yes, would be nice thx :-) I've created a issue for the xmp stuff here : https://github.com/nextcloud/files_photospheres/issues/5

**Comment by MorrisJobke** [comment]
Maybe you also look into integrating this into the new viewer we have started a few weeks ago: http://github.com/nextcloud/viewer/

cc @skjnldsv @jancborchardt

**Comment by skjnldsv** [comment]
Yes, definitely!
We should try to keep the unified design on this!

**Comment by jancborchardt** [comment]
Yep, it’s best to plug into the viewer. :) Also regarding naming, if it’s still on the table – it should be `photospheres` only, because you could also open photospheres from the Mail app, or Social, or or or. :) Nextcloud is not only Files.

**Pull request merged**
