### PR TITLE
revoke summarai.crt

### PR DESCRIPTION
**Pull request by kyteinsky**

### CODE REVIEW

**Comment by nickvergessen** [comment]
needs revocation as usual

**Comment by kyteinsky** [comment]
Hi, sorry I don't understand what I should do, if it was meant for me? Also, the previous cert/key was not used to register any app.

**Comment by nickvergessen** [comment]
No, that's for Matthieu or the sysadmin doing it :P

**Comment by nickvergessen** [comment]
I think you need to revoke `684` which is the original PR: https://github.com/nextcloud/app-certificate-requests/pull/684

**Comment by vitormattos** [comment]
The revoke command was projected to revoke an appid.

At this PR have two actions: revoke and create a new cert.

To work with this tool, will be necessary two PR (the quick way, a PR revoking and a PR adding a new app). To use this PR will be necessary implement a new command, i.e. `certificate:rename`  to consider 3 files changed by PR.

**Comment by kyteinsky** [comment]
I can convert this PR to just add `summary_bot` if you wish to revoke #684

**Comment by nickvergessen** [comment]
> I can convert this PR to just add summary_bot if you wish to revoke https://github.com/nextcloud/app-certificate-requests/pull/684

Might be easier to do both things in separate PRs:
1. Remove summarai in this PR and revoke it
2. New PR to request summary_bot

**Comment by kyteinsky** [comment]
summary_bot.csr is here: #729

**Comment by kyteinsky** [comment]
kind pingu

**Comment by kyteinsky** [comment]
And the folder too?

**Comment by nickvergessen** [comment]
@GretaD did this?

**Comment by GretaD** [comment]
> @GretaD did this?

yes, here 8d7a0006ccdbf3ea0d9cdbfe783875416b49f683,  sorry, forgot to close the ticket

**Pull request merged**
