### PR TITLE
Adding a new certificate for Rainloop app

### PR DESCRIPTION
**Pull request by pierre-alain-b**
Deleting the old certificate (sorry, laptop changed, former rainloop.key not saved... oups...) and proposing a new one.
Of course, the prior key can be revoked!

### CODE REVIEW

**Comment by pierre-alain-b** [comment]
If someone from the team could have a look over this PR, that would be great!
PAB

**Comment by MariusBluem** [comment]
ping @LukasReschke

**Comment by LukasReschke** [comment]
*sigh*

**Comment by LukasReschke** [comment]
Certificate at https://github.com/nextcloud/app-certificate-requests/blob/3ee97e92ce1cddb4d0ef0f201bca995dd6edacf0/rainloop/rainloop.crt – please make sure to upload a new release with that key soonish as the old one will be revoked.

**Comment by pierre-alain-b** [comment]
I sure will!

**Pull request merged**
