### PR TITLE
Update deckimportfromtrello.csr

### PR DESCRIPTION
**Pull request by lucianpricop**
I had to start all over, rebase failed with multiple conflicts.

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @lucianpricop 
Can you share here the URL of app source code's repository?

**Comment by lucianpricop** [comment]
> Hi @lucianpricop Can you share here the URL of app source code's repository?

Hi. Here it is https://github.com/newroco/DeckImportFromTrello

**Comment by vitormattos** [comment]
Hi @lucianpricop 
Maybe will be good if the name of repository is all lowercase or using _ to separate words.

For example:
deck_impor_tfrom_trello

Motivation:
When a new developer clone the repository inside the app or custom_app folder, the directory need to have the same name of app_id and will be more easy to work.

Consequences:
You will need put the app_id equal to repository name.

Only a suggestion.

Waiting for your opinion if you will maintain the current name or not to go to next step.

**Comment by lucianpricop** [comment]
H. Very good suggestion, I renamed the repo https://github.com/newroco/deck_import_from_trello

**Comment by lucianpricop** [comment]
> 

Sure, the minute I have some time.

**Comment by lucianpricop** [comment]
Yes, please, that other one was invalid.

**Comment by vitormattos** [comment]
CRT: https://github.com/nextcloud/app-certificate-requests/commit/65df7c4cafd5a9957bcc07620aead54b930b46cb

**Comment by lucianpricop** [comment]
Thank you!

**Pull request merged**
