### PR TITLE
Update passman csr

### PR DESCRIPTION
**Pull request by animalillo**
@MorrisJobke please check this new csr for the passman app as the old certificate seems to have expired
https://github.com/nextcloud/passman

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@newhinton @brantje Is this fine with you?

**Comment by MorrisJobke** [comment]
The cert in here is valid till 2027:

```
        Validity
            Not Before: Oct 19 19:35:12 2016 GMT
            Not After : Jan 25 19:35:12 2027 GMT
        Subject: CN=passman
```

**Comment by animalillo** [comment]
I requested this because @brantje said the problem with the app was with the current certificate being expired, but we can check other possible causes if that's not the issue

**Comment by brantje** [comment]
@MorrisJobke No need to ask @newhinton ;), i'm still main author.
I've asked @animalillo to update the cert.

**Pull request merged**
