### PR TITLE
Update files_rightclick.csr

### PR DESCRIPTION
**Pull request by NastuzziSamy**
Bad public key exported...

@MorrisJobke (sry)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Next time check this beforehand - we now need to revoke the old cert and deploy the crl in the appstore and all nextcloud instances.

**Comment by NastuzziSamy** [comment]
I am sorry, can you tell me when it will be done ?

**Comment by MorrisJobke** [comment]
> I am sorry, can you tell me when it will be done ?

Was busy the other days ... will do it now ;)

**Comment by MorrisJobke** [comment]
efadeff

**Pull request merged**
