### PR TITLE
Create nebula.csr

### PR DESCRIPTION
**Pull request by DanRiess**
- manage PointCab projects 
- prepare to work with those projects in the separate frontend

Signed-off-by: Daniel Riess <riess.dan@gmail.com>

### CODE REVIEW

**Comment by mgallien** [comment]
@DanRiess can you provide a link to your application source repository ?

**Comment by DanRiess** [comment]
@mgallien is this absolutely necessary? My company wants to host this on a self hosted app store only, because there is some licensing going on. I'm not authorized to release source code at this time

**Comment by blizzz** [comment]
It is not mandatory, nevertheless we always ask for a reference to the sources.

**Comment by blizzz** [comment]
26730433a890560aad2588c58f3bc16e6e7a7395

**Pull request merged**
