### PR TITLE
Create CA_nextcloud.csr

### PR DESCRIPTION
**Pull request by s-rodger**
-----BEGIN CERTIFICATE REQUEST-----
MIIEXTCCAkUCAQAwGDEWMBQGA1UEAwwNbmV4dGNsb3VkLWFwcDCCAiIwDQYJKoZI
hvcNAQEBBQADggIPADCCAgoCggIBAL5HOHMEhKbwTEfYCl1Z04WwWJyPm0/b9/l0
e1X0hdLe06CERSpmd80Jw9EuQlwnz6cyYXzeLui+XNvtrVDx8k+ul+F0F/Co4ziW
lzvaugjvIHqxumZMSn4QZf2RtsqGmJ+1sDraPJiWhNe/fa2oQMqMGGfWKTA6B+9Y
sSfGleDWWUWUEN7FI8JD5899krFSrpbh+jKKaz2YYR9daAQUXAd8YcvtojKTGI/m
pKtipB5WVfvpQ+qLkswcz4qFRmHxnglLwNU6j94wkjQcAn2nPbVo4NBwNwh4xRra
4sd12Ljkho7X76aSV3RvNKvWhIIH9RjT0kdPXF+4DA2SN5qTiIrHvOePTWKNpJkC
4vsaifpBzP1FZqpaWy4QQ43/DHfKjrK2Alk21PcDhHgk2m81bnHcQqlYFROfMM6o
DVXspLtkOiV2qUP8ff0x5Y/ygUTK2mmwyZ133OWIkY1HF/o0p11NWshJRYnc2sF9
1+TEsRoZvFZtP+eQ2zeNDgQWxFu2jI+GbsCAlFholj72RCvOjupSew2GsF1ldIEj
cjJ0GuhCfH+zfJ9NOnPXPYQF9BZOQHdkd++P4YGwMj5LFiqpyXazq8Tn1FU/P9K8
+A2zGhcgbyOOUWTY2TXzHmiymnhnLn6P4iF/JS3/EasoJLLGgWO6W02CpVNpexn7
W34rf8AfAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAWGLjKw51VJY0WNeDWa7b
o3SuKCTeeA0oNpqEbAGjAkxAHfA2Be3GloRl/NW2DHRRbcvgtZq0DHAYuZ0qHwKE
HmX8O3vsbepdS/fw87abCAaugVI017EJRVAI7lXt8E5bUDAdp4VEo8o/5ot7/yH+
BTliFMasqDzifxZ8vGflNedWXHZMIIrvIaOYJbFLHflwgQH8mhwbIsRfalsT6dM2
FfV31joe4LQbiCAhPhmvzC/R0aRNFGjkQE4M4viWCWWRh78k4SSXkR9YknjVl1PA
scWpfxNW5nSu5uI+Qu0L5jkGnCDobvedjaKU6Pg3079LnbEObqenKhaldaOhgXF5
CFptNNJS+PYGqSxmF6lab85Ax6bfYvSimxBWnDPccUFGHlE4i9VZ1Vk2akzRQlS7
CX4IC84UlkkenB9fVW9gWOq03k5b3WPq7FPRVYd995k+o6GIgZyajdl25UiYHcKa
EQd+fkiD3n5uFBcC39yZOLnp0HU+pPzz8p5H7/x4SFs/iRBCrQLeHoQ+5P0t2UhJ
NZUtQL4S1NAqNMHhqrVFTaGRY7XTKV1h76WWxZhHQAI4tC/aps3fd+usSRYu/OKj
Ip3eSAT5rVMtdemzQXsAM8IQGt+Xl+F6Yr+JZc0It+r3ytUSsZjlew3ak6ezFzRd
EA7Ke0FATARHCtbYg2joAHQ=
-----END CERTIFICATE REQUEST-----

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I guess your app is not named "nextcloud-app", right? Could you adjust the filename then? And you have by any chance a publicly available repo somewhere?

**Comment by s-rodger** [comment]
Good day! you're right, the application itself is called Nextcloud, I'm not so long ago on Git, many rules do not know and can do something wrong, unfortunately there is no repository. Please tell me, this certificate will be used when you log into the store itself via https?
--
Отправлено из Mail.Ru для Android пятница, 18 января 2019, 01:59ДП +03:00 от Morris Jobke  notifications@github.com :

**Comment by MorrisJobke** [comment]
The cert says `nextcloud-app`. We have no clear policy, but IMO that name is too generic and should be not used.

cc @jospoortvliet @rullzer @nickvergessen @blizzz Opinions?

@s-rodger Is it possible that you take a bit more specific name for you app that describes it in a better way?

**Comment by nickvergessen** [comment]
`-` is not a valid character for app ids.

**Comment by blizzz** [comment]
yeah, the app id should give a brief glimpse of what can be expected of it.

**Comment by s-rodger** [comment]
renamed CA_nextcloud.csr. When will the certificate be ready? or is it that the right name?
--
Отправлено из Mail.Ru для Android пятница, 18 января 2019, 06:52ПП +03:00 от blizzz  notifications@github.com :

**Comment by s-rodger** [comment]
is that all right now? Create radio777.csr #211
--
Отправлено из Mail.Ru для Android пятница, 18 января 2019, 08:05ПП +03:00 от Morris Jobke  notifications@github.com :

**Comment by MorrisJobke** [comment]
> is that all right now? Create radio777.csr #211

Looks better :)

**Comment by s-rodger** [comment]
Thanks)
--
Отправлено из Mail.Ru для Android пятница, 18 января 2019, 08:41ПП +03:00 от Morris Jobke  notifications@github.com :

**Pull request closed without merging**
