### PR TITLE
Image Converter App certification request

### PR DESCRIPTION
**Pull request by major-mayer**
@MorrisJobke 
Hi, i created a small nextcloud application to convert HEIC/ HEIF images to JPEG.
It works quite good on my own instance, so i would like to share this app to other users over the appstore.

It's my first open source PHP project, especially for nextcloud, so feel free to give me some hints on possible improvements
Here is the repo: https://github.com/major-mayer/imageConverter

### CODE REVIEW

**Comment by blizzz** [comment]
@major-mayer please excuse the delay! 1a1b5fed17b948f47994fc963ace6826fe3389a4

**Comment by major-mayer** [comment]
No problem, this app needs some love before the release anyway ;)

**Comment by major-mayer** [comment]
Just finished the first release, try it out if you want :D 
https://apps.nextcloud.com/apps/imageconverter

**Comment by blizzz** [comment]
> Just finished the first release

great! :)

> try it out if you want :D

I don't have HEIC images, but I am sure you'll get some testers

**Pull request merged**
