### PR TITLE
Create tasks.csr

### PR DESCRIPTION
**Pull request by raimund-schluessler**
@LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Cert at https://github.com/nextcloud/app-certificate-requests/blob/e6b400892fcca963801bc47fea24bbab638947df/tasks/tasks.crt :)

**Comment by jancborchardt** [comment]
Noice! Now that it’s getting published in the appstore, it’s time for @davidpeach to start contributing to the Tasks app ;) https://github.com/nextcloud/tasks
@davidpeach @raimund-schluessler to great collaboration :) :beers:

**Comment by davidpeach** [comment]
oh yes! Just setting up my dev environment with a fresh Ubuntu :) Then I'm on it.

**Comment by raimund-schluessler** [comment]
@LukasReschke Please have a look at https://github.com/nextcloud/tasks/issues/25#issuecomment-267163270. Uploading to the appstore fails.

**Pull request merged**
