### PR TITLE
Create discrete PDF signer csr

### PR DESCRIPTION
**Pull request by salonikumawat28**
### Repository
Repository: https://git.my-d.org/kumawat/nextcloud_discretepdfsigner
(This is a private repository. Is it required for this repository to be public?).

### Info
Discrete PDF signer app for NextCloud adds support to sign PDF files. Users will be able to see `Sign PDF` action menu item for a PDF and when clicked, they will be redirected to the PDF signer provided by Privasphere.

Note: I am employee of Privasphere.

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @salonikumawat28, isn't required to be a public but, if is possible, is good to maintain public. Could you use an open source license and put this repository public?

**Comment by salonikumawat28** [comment]
Thanks for the comment. I have made the repository public . Here is the link  https://github.com/salonikumawat28/NextCloud_DiscretePDFSigner. As suggested by you I have used the LICENCE which you mentioned. Could you please have a look at it and approve the pull request ?

**Comment by salonikumawat28** [comment]
@vitormattos and other repo maintainers: This pull request is open from > 10 days and I am stuck on my work because of this. Can you please review this pull request?

**Comment by nickvergessen** [comment]
Vitor is on vacation this and next week. I will try to ping someone else.

**Comment by mgallien** [comment]
Please find the certificate here https://github.com/nextcloud/app-certificate-requests/commit/cb404821817bd8c40a09c9c728843b39f588f4d2

**Pull request merged**
