### PR TITLE
Create whmcsintegration app

### PR DESCRIPTION
**Pull request by whmcs-global**
### Checklist

- Please include a link to your app repository
- 
https://github.com/whmcs-global/whmcsintegration.git

https://whmcsglobalservices.com/nextcloud-whmcs-module/

### CODE REVIEW

**Comment by mgallien** [comment]
@whmcs-global I suppose that #609 is meant to be closed in favor of this PR ?

**Comment by whmcs-global** [comment]
hi the #609 have wrong CSR we have wrongly putted the signature there for that reason we have request this new one

**Review by mgallien — CHANGES_REQUESTED** [review]
@whmcs-global there is an issue with your pull request
you should add a file named `whmcsintegration.csr` into a subfolder named `whmcsintegration`
so basically the PR should have `whmcsintegration/whmcsintegration.csr`

**Comment by whmcs-global** [comment]
https://github.com/whmcs-global/app-certificate-requests/whmcsintegration

We did the changes please check

**Review by whmcs-global — COMMENTED** [review]
https://github.com/whmcs-global/app-certificate-requests/tree/master/whmcsintegration

**Comment by mgallien** [comment]
> https://github.com/whmcs-global/app-certificate-requests/tree/master/whmcsintegration

@whmcs-global 
this is not the branch that is going to be merged by this PR

`whmcs-global:patch-1` is the branch that is being reviewed here

**Comment by whmcs-global** [comment]
Hi

Added - https://github.com/whmcs-global/app-certificate-requests/tree/patch-1/whmcsintegration

Thanks

**Comment by mgallien** [comment]
@whmcs-global you can find the certificate here
1238daa5b65894d591c5e135dc0006da6dcfc759

**Pull request merged**
