### PR TITLE
SIP Trip Phone certificate signing request

### PR DESCRIPTION
**Pull request by DoubleBastionAdmin**
SIP Trip Phone is a Nextcloud application that acts like a browser phone. It connects to an Asterisk server to make and receive phone calls using SIP over WebSocket and WebRTC. For calls to and from regular phone numbers, a telnyx.com or localphone.com account is needed and a real phone number acquired from one of the two providers of SIP services.

The git repository where the app is developed is [on our server](https://git.doublebastion.com/sip-trip-phone/).

We have no affiliation with Telnyx or Localphone.

Our [contact page](https://www.doublebastion.com/contact/).

### CODE REVIEW

**Comment by vitormattos** [comment]
Good @DoubleBastionAdmin !
Now, can you squash all in only one commit?

**Comment by DoubleBastionAdmin** [comment]
@vitormattos  OK. I just squashed the 3 commits into 1.

**Comment by vitormattos** [comment]
@DoubleBastionAdmin
Can pax_fax/pax_fax.csr go to other PR?

**Comment by DoubleBastionAdmin** [comment]
Ok. I see the problem now. I have to remove pax_fax.csr from this PR. Just a second.

**Comment by DoubleBastionAdmin** [comment]
@vitormattos  Is it OK now ?

**Comment by vitormattos** [comment]
Done!
You will can get the crt here: https://github.com/nextcloud/app-certificate-requests/commit/e7665fb00eb4beca00766a615da0d75c1c4b229d

**Comment by DoubleBastionAdmin** [comment]
Thank you very much @vitormattos for these merges!

**Comment by vitormattos** [comment]
May the force of GNU be with you!

**Pull request merged**
