### PR TITLE
related_resources

### PR DESCRIPTION
**Pull request by ArtificialOwl**

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should be added to sysadmin key chain?
If we deploy from the releases org the key is not even needed to be released, right?
Cc @blizzz

**Comment by blizzz** [comment]
> Should be added to sysadmin key chain? If we deploy from the releases org the key is not even needed to be released, right? Cc @blizzz

you mean given to the maintainer? That would not need to be necessary indeed.

**Comment by ArtificialOwl** [comment]
@vitormattos is anything missing ?

**Comment by vitormattos** [comment]
Hi @ArtificialOwl,
I don't found in a first moment what was the app but, searching here in the Nextcloud organization, I found:
https://github.com/nextcloud/related_resources
Generating now the crt file.

**Review by vitormattos — APPROVED** [review]

**Comment by vitormattos** [comment]
CRT file here: cff51405ffe479b1dd85698208b90f1bf3038b7e

**Pull request merged**
