### PR TITLE
Update emlviewer.crt

### PR DESCRIPTION
**Pull request by lucianpricop**
Updated accordingly.

### CODE REVIEW

**Comment by lucianpricop** [comment]
public repo available here https://github.com/newroco/emlviewer

**Comment by MorrisJobke** [comment]
@lucianpricop This was already requested in #280 are you collaborators? Then I would propose you take the already issued certificate.

**Comment by lucianpricop** [comment]
Yes, we are collaborators. Please ignore, I got misled by the commit message that included this certificate. Thanks

**Comment by lucianpricop** [comment]
Hi. We can't currently publish releases to emlviewer. https://github.com/a11exandru registered the app from his own personal account and now that he's no longer working with us we can't rely on him publishing the releases . Due to https://help.nextcloud.com/t/issue-unlock-transfer-app-ownership/69228 he can't transfer app ownership and even though we have the files .key, .crt, .csr we can't do anything. Registering the app ends in "Signature is invalid: [('rsa routines', 'RSA_padding_check_PKCS1_type_1', 'invalid padding'), ('rsa routines', 'rsa_ossl_public_decrypt', 'padding check failed')]" Uploading a release ends in "You do not have permission to perform this action." 

So let's start fresh, can we get a new certificate, please? Or should we just rename the app and register it as a completely new one? Thanks

**Comment by MorrisJobke** [comment]
> Hi. We can't currently publish releases to emlviewer. https://github.com/a11exandru registered the app from his own personal account and now that he's no longer working with us we can't rely on him publishing the releases . Due to https://help.nextcloud.com/t/issue-unlock-transfer-app-ownership/69228 he can't transfer app ownership and even though we have the files .key, .crt, .csr we can't do anything. Registering the app ends in "Signature is invalid: [('rsa routines', 'RSA_padding_check_PKCS1_type_1', 'invalid padding'), ('rsa routines', 'rsa_ossl_public_decrypt', 'padding check failed')]" Uploading a release ends in "You do not have permission to perform this action."
> 
> So let's start fresh, can we get a new certificate, please? Or should we just rename the app and register it as a completely new one? Thanks

Register a new cert would not solve the issue here. I can unlock the transfer of the app. Then you can upload the app in your name with the existing key and all should be under your name again.

Regarding the problem of the app transfer: I can't reproduce. Best is to report this in the issue tracker once it happens again: https://github.com/nextcloud/appstore

**Comment by lucianpricop** [comment]
Hi. Please unlock the app transfer. What do I need to do? I'd prefer it to be under the account newroco.nextcloud@newro.co so anyone in my team could take care of app releases. 
Thank you very much!

**Comment by MorrisJobke** [comment]
> Hi. Please unlock the app transfer. What do I need to do? I'd prefer it to be under the account [newroco.nextcloud@newro.co](mailto:newroco.nextcloud@newro.co) so anyone in my team could take care of app releases.
> Thank you very much!

It's unlocked already. Just create an account and then upload the app under the existing name with a valid certificate. Then the app is automatically transferred to your account. Authorization that you are the owner happens here via the valid certificate.

**Comment by lucianpricop** [comment]
Thank you. All done here.

**Pull request closed without merging**
