### PR TITLE
Create webapppassword.csr

### PR DESCRIPTION
**Pull request by pbek**
For https://gitlab.tugraz.at/dbp/nextcloud/webapppassword

### CODE REVIEW

**Comment by MorrisJobke** [comment]
2263488

**Comment by pbek** [comment]
Thank you very much, @MorrisJobke!

**Comment by pbek** [comment]
@MorrisJobke, I was trying to use https://github.com/nextcloud/app-certificate-requests/blob/master/webapppassword/webapppassword.crt on https://apps.nextcloud.com/developer/apps/new to register the application but I got an error message `Not a public certificate`. Is anything wrong?

image

**Comment by pbek** [comment]
Other certificates I currently hold are accepted by the form, so it seems it's a problem of the `crt` file...

**Comment by pbek** [comment]
@MorrisJobke, any chance I can get a new webapppassword.crt, or is there a problem with the store, @LukasReschke, @rullzer?

**Comment by nickvergessen** [comment]
It seems like a last trailing `-` is missing on the last line. There should be 5 after `END CERTIFICATE`

**Comment by pbek** [comment]
You are right, @nickvergessen. Thank you very much! I made a pull request #321 that adds the missing character.

**Pull request merged**
