### PR TITLE
Create snappymail.csr

### PR DESCRIPTION
**Pull request by the-djmaze**
Signed-off-by: the-djmaze <3752035+the-djmaze@users.noreply.github.com>

### Checklist

- Please include a link to your repository
https://github.com/the-djmaze/snappymail

```Then post the contents of your APP_ID.csr (e.g. ~/.nextcloud/certificates/news.csr) on [on our certificate repository](https://github.com/nextcloud/app-certificate-requests) as pull request and configure your GitHub account to show your mail address in your profile.```
Sorry, NO.
I use email address for every service. So it's like:
- nextcloud@domain
- github@domain

So issues may be reported to: nextcloud-app-certificate@snappymail.eu

Also the registration on apps.nextcloud.com is totally wrong. Somehow i login as `X` and not something valid.
And login with only `Firstname` is good, many people have the same firstname.
So to get my app registered is really a messy process

### CODE REVIEW

**Comment by vitormattos** [comment]
Hi @the-djmaze I created a PR suggesting a new text in documentation and mentioned this PR. Could you check if the new text is ok?

Only to make easier the PR, here is the link of source code of app:

https://github.com/the-djmaze/snappymail/tree/master/integrations/nextcloud/snappymail

**Comment by nickvergessen** [comment]
The reason for the email address is that in case a security issue is found by/reported to us we need a way to contact you reliably. At the same time we can not maintain a second place for a mail list. Hope you are fine with just posting it here, otherwise we will have to see how we can post it here in an encrypted way still allowing the security team to contact you

**Comment by szaimen** [comment]
> The reason for the email address is that in case a security issue is found by/reported to us we need a way to contact you reliably. At the same time we can not maintain a second place for a mail list. Hope you are fine with just posting it here, otherwise we will have to see how we can post it here in an encrypted way still allowing the security team to contact you

Maybe by using a guest account on c.nc.c? But I guess we would need a mail address for that too...

**Comment by the-djmaze** [comment]
@nickvergessen ok fine.
I've added an email address for that case.

**Review by vitormattos — APPROVED** [review]

**Comment by vitormattos** [comment]
your crt here: 9f17a38297c9861e2c3af3da3f4bdfaab7fac29d

**Comment by the-djmaze** [comment]
Thanks!

**Pull request merged**
