### PR TITLE
integration_homeassistant new certificate

### PR DESCRIPTION
**Pull request by poulou0**
Hello there,

My app is the [integration_homeassistant](https://github.com/poulou0/nextcloud-homeassistant-integration)
I have no idea why my last certificate was revoked.

<details>
  <summary>Trying to Install the app gives this</summary>
   
  image
</details>

and I get something similar when I try to upload a new version of the app.

I still have the old private key, in case its possible to re-enable it.. I don't mind changing it again, but I would like to understand what happened and it got revoked.

Thank youuu

### CODE REVIEW

**Comment by mgallien** [comment]
@poulou0 you created https://github.com/nextcloud/app-certificate-requests/pull/667
I guess the current state is that we did what was requested in https://github.com/nextcloud/app-certificate-requests/pull/667

can you check ?

**Comment by poulou0** [comment]
Hey, thank you for the quick reply.

Yes indeed and I still have the private of the one in https://github.com/nextcloud/app-certificate-requests/pull/667, I just checked with a backup that I made that day.

It feels like the problem is there though.
I published v0.0.3 of my app with the certificate in https://github.com/nextcloud/app-certificate-requests/pull/667.

<details>
  <summary>When I try to install v0.0.3 in my setup I get this error!</summary>
   
  image
</details>

<details>
  <summary>When I try to upload a new v0.0.4 i get this</summary>
   
  Screenshot from 2024-03-12 18-27-48

  </details>

But if i try to install my app from [this nextcloud demo](https://en.nextfiles.de/demo/), it installs normally 🤔

Any help is welcome :+1:

**Comment by mgallien** [comment]
@poulou0 I am sorry as I may need more time
could you try reaching out for help via our community Talk room ?
https://cloud.nextcloud.com/call/xs25tz5y
with more time, I should be able to dig and understand how to help you but as I am unfamiliar with some parts of teh stack, I may need some time (especially with questions on the AppStore)

**Comment by bigcat88** [comment]
maybe we can get another try to regenerate it?

**Comment by poulou0** [comment]
Hey, thanks for the quick reply!

Do you mean to merge this PR?
No problem, sure! :)

Older versions of the app will be deleted, right?
But any newer version that I upload will come as an update for the existing installations if I remember correctly.
Can you confirm that?

Regardless, I think we should go ahead and merge :+1:

**Comment by mgallien** [comment]
@poulou0 you can find the new certificate here ef061f1b33049d1df905f3ab15ded270741a27f5

**Pull request merged**
