### PR TITLE
Create ping.csr

### PR DESCRIPTION
**Pull request by derbenx**
https://github.com/derbenx/nextcloud-ping

### Checklist

- Please include a link to your app repository

### CODE REVIEW

**Comment by mgallien** [comment]
@derbenx I am sorry

**Comment by mgallien** [comment]
@derbenx I am sorry
we would prefer not to have a Nextcloud app published on the app store and being usable to perform ping and portscan from a Nextcloud server
so we prefer to refuse generating a certificate to publish an app dedicated to that
we believe the security downside of having this being abused to perform remote attacks is bigger than the few people that may find it convenient to use a Nextcloud instance to perform pings or port scans
I understand that this may be frustrating for you

**Comment by vitormattos** [comment]
Just asking to clarify a curiosity, what kind of risks could it bring?

I think it would be interesting to have apps focused on security on Nextcloud.

I believe that existing apps like this respect the "[freedom zero](https://www.gnu.org/philosophy/free-sw.html#run-the-program)" of Free Software:
> _The freedom to run the program as you wish, for any purpose (freedom 0)._
Maybe the decision to install apps like this, is at admin of an instance.

**Comment by derbenx** [comment]
I made this because I needed a portscanner for debugging network situations, finding network devices and such. It lets me sweep my lan to see what or who's active and debug open/firewalled ports. Granted many admins could already have such a tool, but this runs from the server side, not locally. This allows you to check your server network from anywhere (if online). It's actually safer than having SSH or screen sharing software open to the world.

Many antivirus softwares do flag executable programs that do port scanning as PUPs because some people misuse them for DDOS attacks, they are used with Remote Access software to run remotely and automatically. To use this as a DDOS, the program would need to be modified for the Distributed part of the Distributed Denial of Service and you'd need access to several nextcloud servers to DDOS too. Also, as a DDOS program, usually they open up to hundreds of ports at a time, mine just scans one at a time. It's actually really slow for any kind of attack between the ajax calls. :P

Typically the average user doesn't need this, but for admins it a valuable tool, especially if the alternative is a sketchy closed source download. As an optional app, that the admin has to manually install.. and even then install fping for Linux, I don't see this issue. It can't possibly be any worse than something like occweb (now depreciated). Chances are that anyone installing it, as an admin, will know what to do with it and restrict access accordingly. I mention that right there on the landing page for those who don't.

**Comment by mgallien** [comment]
@derbenx those comments are mostly mine and do not necessarily represent the opinion of my employer

> I made this because I needed a portscanner for debugging network situations, finding network devices and such. It lets me sweep my lan to see what or who's active and debug open/firewalled ports. Granted many admins could already have such a tool, but this runs from the server side, not locally. This allows you to check your server network from anywhere (if online). It's actually safer than having SSH or screen sharing software open to the world.

Imagine having a network that is representative of recommendations for the deployment of Nextcloud (and any other web applications to be accessible from internet).
You would use a DMZ zone to host the web application and its services (unless they can be put on a private separate network). This would be unable to access the primary network with workstations accessing the web application.
This would be also reachable from external network for users on the move.

What would be the use of being able to do ping in such a restricted network. I would say that is is of no use. To complement that, usually network router include the ability to do pings to debug network issue from the device responsible for the network management.

> Many antivirus softwares do flag executable programs that do port scanning as PUPs because some people misuse them for DDOS attacks, they are used with Remote Access software to run remotely and automatically. To use this as a DDOS, the program would need to be modified for the Distributed part of the Distributed Denial of Service and you'd need access to several nextcloud servers to DDOS too. Also a DDOS program usually opens up hundreds of ports at a time, mine just scans one at a time. It's actually really slow for any kind of attack between the ajax calls. :P
> 
> Typically the average user doesn't need this, but for admins it's a valuable tool, especially if the alternative is a sketchy closed source download. As an optional app, that the admin has to manually install.. and even then install fping for Linux, I don't see this issue. It can't possibly be any worse than something like occweb (now depreciated). Chances are that anyone installing it, as an admin, will know what to do with it and restrict access accordingly. I mention that right there on the landing page for those who don't.

I would never install this app on a Nextcloud server. Not because I do not trust you but because any developer can be mistake and the risk of this being abused to perform attack via my own infrastructure would be a shame for me.

My question is really why do you think people would use this on a Nextcloud server via web rather than on their network management infrastructure or via command line directly from the hosting platform for your server ?

**Comment by mgallien** [comment]
@derbenx sorry for the mistake
I failed to find a way to unhide your comment
I am really sorry

> I made this because I needed a portscanner for debugging network situations, finding network devices and such. It lets me sweep my lan to see what or who's active and debug open/firewalled ports. Granted many admins could already have such a tool, but this runs from the server side, not locally. This allows you to check your server network from anywhere (if online). It's actually safer than having SSH or screen sharing software open to the world.
> 
> Many antivirus softwares do flag executable programs that do port scanning as PUPs because some people misuse them for DDOS attacks, they are used with Remote Access software to run remotely and automatically. To use this as a DDOS, the program would need to be modified for the Distributed part of the Distributed Denial of Service and you'd need access to several nextcloud servers to DDOS too. Also a DDOS program usually opens up hundreds of ports at a time, mine just scans one at a time. It's actually really slow for any kind of attack between the ajax calls. :P
> 
> Typically the average user doesn't need this, but for admins it's a valuable tool, especially if the alternative is a sketchy closed source download. As an optional app, that the admin has to manually install.. and even then install fping for Linux, I don't see this issue. It can't possibly be any worse than something like occweb (now depreciated). Chances are that anyone installing it, as an admin, will know what to do with it and restrict access accordingly. I mention that right there on the landing page for those who don't.

**Comment by mgallien** [comment]
I would also like to clarify what is the intended purpose here.
We do not want to ease install of this application via the Nextcloud appstore as it could make it easy for people to make themselves vulnerable without realizing it
Any experienced admin wanting to make use of this application is free to install and use it directly on their servers. They would just need to do a manual app installation. That way everybody is happy

**Pull request closed without merging**
