### PR TITLE
Data Service App

### PR DESCRIPTION
**Pull request by ksainc**
Link to app repository 

https://github.com/ksainc/data

### CODE REVIEW

**Comment by nickvergessen** [comment]
Data was denied in the past, because it can cause too many confusions when working with code:
https://github.com/nextcloud/app-certificate-requests/pull/272

Can you pick something else?

**Comment by ksainc** [comment]
I can, do you have any recommendations? Lol

**Comment by ksainc** [comment]
would "dio" work and be permitted?

**Comment by nickvergessen** [comment]
reading the readme and the info.xml I would have the following suggestions, because it totally fits into https://docs.nextcloud.com/server/latest/user_manual/en/groupware/index.html

- groupware_data_provider
- groupware_data_service

**Comment by ksainc** [comment]
Okay, are good suggestions.

But I really want to keep the url length as short a possible without special character, as these urls might have to be entered manually sometimes on phones with a T9 keypad. Anyway.

Any objections to "dio" Data In/Out?

**Comment by nickvergessen** [comment]
fine by me as well

**Comment by ksainc** [comment]
Thank you. I will rename the folder and resubmit

**Pull request closed without merging**
