### PR TITLE
Request: user_sql

### PR DESCRIPTION
**Pull request by andyboeh**
I kindly ask for a certificate for user_sql, thanks.

### CODE REVIEW

**Comment by LukasReschke** [comment]
Can you link to the app? I don't find it on your GitHub profile or so.

**Comment by andyboeh** [comment]
Sorry, i don't use github for hosting, of course: 
Repo: https://code.rnb-consulting.at/diffusion/USQL/
OC Appstore: https://apps.owncloud.com/content/show.php/user_sql?content=155512

**Comment by LukasReschke** [comment]
Thanks. You should have gotten a message on the appstore for identity verification.

**Comment by andyboeh** [comment]
Here is the verification string: Nh8ZrdEWYYqRnMVhgQ3DJG

**Comment by LukasReschke** [comment]
Thanks.

**Comment by LukasReschke** [comment]
You can find your issued certificate at https://github.com/nextcloud/app-certificate-requests/blob/master/user_sql/user_sql.crt

**Pull request merged**
